ShareX.HelpersLib/Helpers/Helpers.cs
ShareX.UploadersLib/FileUploaders/FTP.cs
ShareX.UploadersLib/FileUploaders/FTP/FTPAccount.cs

Several changes were made to fix the encoding of ftp dirpaths and allow
uploads to folders with non-ascii characters:
FTPAccount.cs
This fixes issue #372, which was reproduced with the following account
config on a local ftp server (import from clipboard on destination
settings):
```json
{
"Protocol": "FTP",
"Name": "New account",
"Host": "localhost",
"Port": 21,
"Username": "test",
"Password": "test",
"ServerProtocol": "ftp",
"SubFolderPath": "DEV/grhh本人%",
"BrowserProtocol": "http",
"HttpHomePath": "",
"HttpHomePathAutoAddSubFolderPath": true,
"HttpHomePathNoExtension": false,
"IsActive": false,
"FTPSEncryption": "Explicit",
"FTPSCertificateLocation": "",
"Passphrase": null,
"Keypath": null
}
```

Fix issue #372

---

ShareX.UploadersLib/FileUploaders/FTP/FTPAccount.cs

Fix issue #436 
This return statement was double encoding filename hence the extra encoding on the "%" sign in the URL in clipboard.
return Uri.EscapeUriString(httpHomeUri.Uri.ToString());

Fix issue #436

---

ShareX.UploadersLib/FileUploaders/GoogleDrive.cs
ShareX.UploadersLib/Uploader.cs

Updates GoogleDrive & Uploader to include the metadata in a multipart/related when sending to Google Drive. May also fix some cases where files uploaded to gdrive were broken.

#404 - Use multipart/related for GDriveSDK uploads

---

ShareX.UploadersLib/FileUploaders/AmazonS3.cs
ShareX.UploadersLib/FileUploaders/AmazonS3Region.cs
ShareX.UploadersLib/FileUploaders/AmazonS3Settings.cs
ShareX.UploadersLib/ShareX.UploadersLib.csproj
ShareX.UploadersLib/Uploader.cs

There is no functional change here, it's just clearer why an upload fails now. Uses the `Errors` collection of `UploadResult` instead of throwing exceptions.

Made Amazon S3 uploader more robust, additional error handling. Moved classes to their own files.

---

README.md

Extract Wikipedia article into README so this README can be linked to instead, addressing the article's [issues](https://en.wikipedia.org/wiki/Talk:ShareX). If accepted, the Wikipedia article can be stripped of the sections covered here.

Extract Wikipedia article into README

---

ShareX.UploadersLib/FileUploaders/FTP.cs
ShareX.UploadersLib/FileUploaders/SFTP.cs

Fix for Issue ShareX/ShareX#802
Do not url-encode file names for (S)FTP upload.
This is not necessary and a valid URL is created afterwards resulting in double-url-encoded URLs which is message and effectively destroys UTF8 based filenames e.g. Japanese.

Do not url-encode file names for (S)FTP upload.

---

ShareX.HelpersLib/Helpers/URLHelpers.cs

Update URL regex with updated Gist (Same one as before just updated: https://gist.github.com/729294)
This is to match odd URLs, I have tested with the provided example in #686 and it matches that URL correctly.

Update URL regex to match odd URLs

---

ShareX.ScreenCaptureLib/RegionHelpers/AreaManager.cs

related #936 
The cancel operation does not reset the state back to be ready for a new region.  The end operation is needed to reset the state.
fixes issue:
<kbd>Insert</kbd> to start.
<kbd>Right click</kbd> to cancel it.
<kbd>Left hold</kbd> or <kbd>Insert</kbd> not starts region selection.
But If I cancel it with <kbd>Delete</kbd> then it works fine.

resolve right click cancel to insert state

---

ShareX.HelpersLib/Properties/Resources.de.resx

changed "Handbuch" to "manuell" 2 times, as it is no (user) manual

fixed translation errors in Resources.de.resx

---

Greenshot.ImageEditor/Drawing/TextContainer.cs

text == null and newText == null leads to "null.Equals(null)" check

Fix possible null dereference at ChangeText

---

Greenshot.ImageEditor/Drawing/DrawableContainer.cs

It was checked before the first dereference and was not checked before the
second one

Fix a null check for newParent at SwitchParent

---

ShareX/Controls/HotkeySelectionControl.cs
ShareX/Forms/HotkeySettingsForm.cs
ShareX/Forms/MainForm.cs
ShareX/HotkeyManager.cs
ShareX/TaskHelpers.cs

Hotkeys are unregistered temporarily until the user enables them again. The hotkey form now also reacts to enabling and disabling hotkeys. When hotkeys are disabled, a new hotkey is saved but not registered. Resetting hotkeys to default also enables them again.

Issue #846: Unregister hotkeys when disabling them.

---

ShareX/ImageData.cs
ShareX/Properties/Resources.Designer.cs
ShareX/Properties/Resources.resx
ShareX/WorkerTask.cs

Reopens the save dialog after the exception window has been confirmed. This fix should prevent losing pictures on errors (see issue #1008).
An easy way to provoke an error on saving:
1. Create drive mapping to a folder: ``subst S: C:\Test``.
2. Activate post capture task ``Save image to file as...``.
3. Create breakpoint before the image is saved.
4. Capture a image and select the drive ``S:`` as location.
5. While the program is stopped, unmap the drive via ``subst S: /D``.
6. Remove breakpoint, continue execution. An exception is shown.
7. After the exception the file dialog is shown again.

Reopen save as dialog on errors after capture

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs

Currently, when a file is uploaded, and an error is generated, a JSON
serialization error is thrown because of the unexpected JSON output.
This commit fixes that.
To illustrate the problem:
Current error:
Error after this fix:

fixes Newtonsoft.Json.JsonSerializationException with OwnCloud upload

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs

This fixes an issue where a file in a hash would cause the uploaded
file to be truncated after the hash, causing the share function to
fail subsequentially because the file was not found. Only the PUT
request to upload the file requires the hash to be encoded, as it's
part of the URL, while the POST request for the share has the path in
the POST parameters.
closes #1148.
Illustration:
Currently:
After fix:

fixes issue with hash in filename when uploading to owncloud

---

ShareX.ScreenCaptureLib/Properties/Resources.ru.resx

Very small change.
Russian translation only.

Fixed "W:" and "H:" in rectangle info text being swapped

---

ShareX.HelpersLib/Properties/Resources.Designer.cs
ShareX.HelpersLib/Properties/Resources.resx
ShareX/Enums.cs
ShareX/TaskHelpers.cs
ShareX/WorkerTask.cs

I've implemented the functionality discussed in #1265. This has been added as an After Capture task that can be enabled. If enabled it shows windows explorer after capture with the new screenshot highlighted. See screenshots below.
I've added the localized translation for English for 'Show file in explorer'. I wasn't sure how you do the translations for the other resource files?
Please let me know if there are any issues.
Thanks

Added post capture task to show in explorer #1265

---

ShareX.HelpersLib/SingleInstanceApplication/ApplicationInstanceManager.cs

Current process is as follows:
1. Invoked .exe gets the semaphore
2. Invoked .exe sets `InstanceProxy` values in running exe
3. Invoked .exe causes thread to spawn in running exe
4. New thread in running .exe reads values from `InstanceProxy`
5. Invoked .exe releases the semaphore
The problem is that there is no guarantee on how fast new threads in
running .exe will spawn and read values from `InstanceProxy`. This PR
addresses that by moving the semaphore release from the invoked .exe to
the thread spawned in running .exe.
This means that an invoked .exe can't change `InstanceProxy` until 
running .exe has processed the previous call.

Handle multiple context menu selections - Move semaphore release

---

ShareX.HelpersLib/SingleInstanceApplication/ApplicationInstanceManager.cs
ShareX.HelpersLib/SingleInstanceApplication/InstanceProxy.cs
ShareX/Program.cs

Reworked single instance code to better handle being launched with
context menu.
Previously:
- On launch, process would try to open an `EventWaitHandle`. If it
didn't exist, then process assumed it was first and created it
- Multiple processes launching at same time would all see the
`EventWaitHandle` did not exist before any process could create it
- This led to multiple instances of program running (as discussed at https://github.com/ShareX/ShareX/pull/1382#issuecomment-194561241)
Now a mutex is used for proper synchronization:
- Processes will all try to open the mutex. Only first one will succeed
- Process that opens the mutex will setup the `EventWaitHandle`
- Other processes won't get the mutex and will be directed to use the
`EventWaitHandle` to pass their command line args to the …

Proper Single Instance Implementation

---

ShareX.UploadersLib/FileUploaders/Localhost/LocalhostAccount.cs

Properly expand local folder variables (such as Desktop and My
Documents).
Corrects bug from 35cb75d055a7c250c4fdd8d19a42e1215fd1b6bc

Expand Folder Variables

---

ShareX.UploadersLib/FileUploaders/Pomf.cs

The preferred domain name of pomf.lesderid.net was recently changed to p.fuwafuwa.moe. The old domain still works (both uploading new files and downloading existing ones), but might be deprecated at some point in the (far) future.
Sorry for the commit noise.

Update URL of pomf.lesderid.net to p.fuwafuwa.moe

---

Greenshot.ImageEditor/Forms/ImageEditorForm.cs

Fixes error introduced in last Greenshot merge

Make rect default selection in Greenshot

---

Greenshot.ImageEditor/Configuration/EditorConfiguration.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.Designer.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.cs
Greenshot.ImageEditor/Forms/ImageEditorForm.Designer.cs
Greenshot.ImageEditor/Forms/ImageEditorForm.cs

Adds setting to allow user to save the last drawing mode used in Greenshot
so that it will be selected next time image editor is opened.
Also adds setting to config file to allow user to change the default
drawing mode.
Closes #1609

Default and last drawing modes in Greenshot

---

ShareX.UploadersLib/FileUploaders/GoogleDrive.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

I was trying to find some way to get around the fact that Google Drive encodes videos after uploading them from ShareX, which can take quite a while. All I want is a direct link to the uploaded file.
One way to create a direct link is to just append the ID to a URL, as such:
`$"https://drive.google.com/uc?id={upload.id}"`.
... but I figured it would be better to leverage the response somehow, so instead I tried using the `webContentLink` entry from `result.Response`, which contains the above mentioned link.
But by default `webContentLink` is bundled with the query `?export=download`, which seems to add `Content-Disposition: attachment` to the HTTP headers, forcing the browser to download the file instead of just viewing it. Stripping away said query parameter seems to fix that, and the …

Add "Use direct link" setting to Google Drive uploader

---

Greenshot.ImageEditor/Configuration/CoreConfiguration.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.Designer.cs

Change to allow any icon size that is a multiple of 8 and don't let user
choose an invalid size.
Closes #1651

Lock Greenshot icon sizes to multiples of 8

---

Greenshot.ImageEditor/Configuration/EditorConfiguration.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.Designer.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.cs
Greenshot.ImageEditor/Forms/ImageEditorForm.cs

When Automatically resize window is set:
1. Fixes #1640 which was caused by mixing screen and working area
coordinates
2. Moves window up and left to try and fit it in the working area
3. Adds option to maximize the editor window when it is larger than
working area (such as when capturing full desktop or multi-monitor).

Size and position Greenshot editor window to be on screen

---

Greenshot.ImageEditor/Forms/EditorSettingsForm.cs

Size allowed to be multiple of 8 not 16

Fix Greenshot editor icon size restraint

---

Greenshot.ImageEditor/Forms/ImageEditorForm.cs

Scales based on approximate number of icons displayed and size of icon
over 16 pixels

Scale Greenshot editor window size when icons larger than default

---

ShareX.UploadersLib/UploadersConfig.cs

To fix issue #1720 (https://github.com/ShareX/ShareX/issues/1720).
Pomf.cat's uptime according to http://pomfstatus.sapph.io/ is abysmal and shouldn't be enabled as the default Pomf uploader host destination.

Change Pomf Default to more reliable host

---

ShareX.HelpersLib/Helpers/Helpers.cs

Currently Google Dart source files are not treated as text files, meaning they're uploaded using the currently selected file uploader. This change is to fix the issue.

Add Dart language source files as a text file type

---

ShareX/Forms/MainForm.Designer.cs
ShareX/Forms/MainForm.cs

It's still not drawing the icon **while** resizing.

Redraws blue information icon after column resize. Partially fixes #1831.

---

ShareX.HelpersLib/Forms/DebugForm.cs

Fixes the error message in debug screen when pressing loaded assemblies button, by not trying to include dynamic assemblies as these assemblies don't have a location.
Alternative way to fix this is referenced here: [https://github.com/dphoebus/Zbu.ModelsBuilder/commit/1cfb31f24ee6cf58c316519c8554384e1f22a0ec](https://github.com/dphoebus/Zbu.ModelsBuilder/commit/1cfb31f24ee6cf58c316519c8554384e1f22a0ec)
Fixes [706](https://github.com/ShareX/ShareX/issues/706) and [1860](https://github.com/ShareX/ShareX/issues/1860).

Fixes the error message in debug screen when pressing loaded assemblies button, by not trying to include dynamic assemblies.

---

ShareX.HelpersLib/ApplicationInstanceManager.cs

Make IPC channel name unique per user to fix access denied problems on
multiuser systems.
Fixes #1994.  May also fix #1462 and #1509

Add user name to IPC channel name

---

ShareX.UploadersLib/ImageUploaders/Picasa.cs

Skip trying to parse response if it is null. Errors will get reportedly
properly.
Fixes #1983

Don't parse null response string when Picasa upload fails

---

ShareX.HelpersLib/Native/NativeEnums.cs
ShareX.HelpersLib/Native/NativeMethods.cs
ShareX.HelpersLib/Native/NativeMethods_Helpers.cs
ShareX.HelpersLib/Native/WindowInfo.cs

UWP apps that aren't shown are 'cloaked'
Fixes #1960

Hide background UWP apps from window capture options

---

ShareX.ScreenCaptureLib/Forms/ScrollingCaptureForm.cs

TrimTopEdge > 0 was checked twice instead of TrimRightEdge

Fix trim edge checking

---

ShareX/Forms/MainForm.cs
ShareX/TaskHelpers.cs

Added capability to pass a file path as a parameter to the ImageEditor
CLICommand so it doesn't prompt an open file dialog if a valid image path
has been given in the CLI already and fixes #1990.

CLI for Edit Image

---

ShareX.UploadersLib/ImageUploaders/Chevereto.cs

Imgfly.me is now serving with HTTPS and it's needed to update the link for properly access the API.

Updated imgfly.me to HTTPS

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs

Overlooked this in my last commit since it worked fine without it at in the non dev version.

Fixed missing header for dev version of Nextcloud

---

ShareX.HelpersLib/Enums.cs
ShareX.ImageEffectsLib/Manipulations/Resize.cs

My main issue with the resizing image effect is there should be an option for those (like myself) who would like to only resize if the image is smaller! Currently you either get big images resized or you get all images resized, but not small images resized while big images are left alone. I propose we use three modes to choose from for resizing options. The modes would be the following: resizing all images, resizing only bigger images, and resizing only smaller images . The default being to resize all images.

ResizeIfSmaller Option for Resizing

---

ShareX/Forms/QRCodeForm.resx

Changed 'Ctrl' to 'Control' for a multi-language keyboard support.
According to this issue: https://social.msdn.microsoft.com/Forums/vstudio/en-US/9ab50ba0-9be1-49e8-b4f6-7cfd97eccf10/msbuild-cannot-process-resource-files?forum=msbuild

Changed Ctrl to Control

---

ShareX.UploadersLib/APIKeys/APIKeys.cs
ShareX.UploadersLib/FileUploaders/GfycatUploader.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs
ShareX.UploadersLib/UploadersConfig.cs

The config tab doesn't have an icon for gfycat, because I can't find one to use.
Supports anonymous or authenticated uploads, and gives the option to either post gfycats public or private.
Also might theoretically stop that embarrassing issue with incorrect uploads, that some people have mentioned.

Updated gfycat to use newer oauth2 api

---

Greenshot.ImageEditor/Forms/AboutForm.Designer.cs
Greenshot.ImageEditor/Forms/ColorDialog.Designer.cs
Greenshot.ImageEditor/Forms/DropShadowSettingsForm.Designer.cs
Greenshot.ImageEditor/Forms/EditorSettingsForm.Designer.cs
Greenshot.ImageEditor/Forms/ResizeSettingsForm.Designer.cs
Greenshot.ImageEditor/Forms/TornEdgeSettingsForm.Designer.cs

Set AutoSize to true to ensure forms are properly displayed.
Fixes #2406.

AutoSize Greenshot forms

---

ShareX.UploadersLib/FileUploaders/AmazonS3.cs
ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs

Fixes an issue where random paths are being calculated twice - once on upload and once on url generation - causing the URL path to be different than the upload path.

Fix S3 Uploads with random paths

---

ShareX/TaskHelpers.cs

Fix #2499 
Balloon notification for color picker copied to clipboard will not show if no notifications is set in settings

Screen color picker notifications

---

ShareX.UploadersLib/FileUploaders/AzureStorage.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Azure has different environments for Azure Germany, Azure China and Azure USGov, and potentially different environments when using an Azure Stack instance.
This PR adds configuration options for these Azure environments to allow the Azure storage uploader to upload to non-'Global' environments.

Support configurable environments for Azure storage

---

ShareX.HelpersLib/Forms/MonitorTestForm.nl-NL.resx

In ShareX 11.7, the test patterns have wrong names, this is also according to the code: https://github.com/ShareX/ShareX/blob/15e63e8a925208a85eb7ef7599c6de62b9e5cea1/ShareX.HelpersLib/Forms/MonitorTestForm.cs#L175
Changed names to match the same order as inside the actual code

Update translation error in test screen patterns

---

ShareX.UploadersLib/FileUploaders/AzureStorage.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Users can now add a custom domain to be used. Since uploading over HTTPS to a custom domain is currently forbidden in Azure, we still use the normal endpoint for uploading over HTTPS, but then use a custom domain to serve to the user instead.
Fixes issue #2318. Thanks @wi5nia for the initial Azure support.

Custom Domain Support for Azure Blob Storage

---

Greenshot.ImageEditor/Drawing/ArrowContainer.cs
Greenshot.ImageEditor/Drawing/Surface.cs
ShareX/HotkeyManager.cs

Hi, I have checked this solution with the [CodeRush for Roslyn](https://marketplace.visualstudio.com/items?itemName=DevExpress.CodeRushforRoslyn) static analyzer and found several things to improve:
1. [Logical OR expression has opposite operands](https://documentation.devexpress.com/CodeRushForRoslyn/118112/Static-Code-Analysis/Analyzers-Library/CRR0012-Logical-OR-expression-has-opposite-operands) in two places
2. [Unnecessary conditional](https://documentation.devexpress.com/CodeRushForRoslyn/118219/Static-Code-Analysis/Analyzers-Library/CRR0023-Unnecessary-conditional)
3. I also found [this palce](https://github.com/ShareX/ShareX/blob/206a79d86e752a5e6e9aadf2e2f7348ee9438645/Greenshot.ImageEditor/Configuration/CoreConfiguration.cs#L501) quite strange, but it is way too strange for …

Static Analysis Results

---

ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

The proper condition should've been
`if(form.IsAnnotationMode && !form.IsEditorMode)`
but I guess checking for null is more robust here

Fix error when pressing F1 during image editing

---

ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

This is a pull request to fix #2673 and #2820.
The issue is that `InputManager` doesn't have the currently touched point location at the moment of `BaseShape.OnCreating()` and `ShapeManager.GetIntersectShape()`.
Since mouse moves continuously, this is not a problem (or at least not noticable). However, since no mouse movement happens between previous MouseUp and next MouseDown event when using touch, this issue becomes important.
So, forcing `InputManager` to update on the beginning of `ShapeManager.StartRegionSelection()` fixes the issue.
(At first I wanted to do it inside `BaseShape.OnCreating()` but then I figured that selecting existing shapes also suffer from the same issue in touch screens. So putting it on the beginning of `StartRegionSelection()` seems more logical)

Fixed an issue with touch screens not being able to select region/draw/select drawing correctly

---

Greenshot.ImageEditor/Greenshot.ImageEditor.csproj

This fixes the following error the user might encounter when building from CMD:
```
"C:\Users\Charles\Git\ShareX\ShareX\ShareX.csproj" (cible par défaut) (1) ->
"C:\Users\Charles\Git\ShareX\Greenshot.ImageEditor\Greenshot.ImageEditor.csproj" (cible par défaut) (3:2) ->
(_CheckForInvalidConfigurationAndPlatform cible) ->
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.target
s(748,5): error : The OutputPath property is not set for project 'Greenshot.ImageEditor.csproj'.  Please check to make
sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Window
sStore'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file …
```

Add default build configuration and platform for Greenshot Editor

---

ShareX.UploadersLib/FileUploaders/Pomf.cs

* Commented out:
* Filebox because - it's down
* sugoi.vidyagam.es - because it's dangerous according to ESET, and [here](https://sitecheck.sucuri.net/results/sugoi.vidyagam.es)
* Added several cool clones
* Added another clone tracker

Updated down sites, added clones

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

When annotating image use middle mouse buttnon to pan image and all shapes with it.
Also fixes crop not moving shapes.

Add panning to image annotate

---

ShareX.UploadersLib/Forms/OCRSpaceForm.Designer.cs
ShareX.UploadersLib/Forms/OCRSpaceForm.cs

Also, sets the focus to the result textbox upon completion (which will also select all of the text)
Closes #2852

Support CTRL+A in OCR results window

---

ShareX.HelpersLib/Controls/MyListView.cs
ShareX.HelpersLib/ListViewColumnSorter.cs
ShareX.HistoryLib/HistoryForm.cs

Checks if the column header Tag is a DateTime object and if so, sorts the column by date. This approach prevents performance impact when sorting columns that are not dates and allows any user of MyListView to tag a column to be sorted by date. Supports expansion to other sorting formats.
Tested with history of 80,000 items.
Closes #1685

Properly sort columns with dates in listviews

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/RegionCaptureTasks.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs

Show options menu in editor mode and hide region capture related settings.
Use options reference in editor mode instead of options clone to be able to save settings. Need to override settings in region capture form for this to work.

Show options menu in editor mode and save options

---

ShareX.HelpersLib/WindowState.cs
ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/RegionCaptureOptions.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs

This option saves window state, position and size when window closing and when user re open editor this window states will be applied.

Added option to remember editor window state, position and size

---

ShareX.HelpersLib/Forms/ScreenTearingTestForm.cs
ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/Forms/RegionCaptureLightForm.cs
ShareX.ScreenCaptureLib/Forms/RegionCaptureSimpleAnnotateForm.cs

This fixes the annoying incorrect capture region problem #1800, and I think that this will not cause any significant layout problems for different DPIs. (For example `ShareX.HelpersLib.MonitorTestForm` is a fullscreen form which does not contain `AutoScaleDimensions` assigns, but it works fine.)
However, while this works well on my laptop with different text scale settings, it should be checked on different computers as well.

Removed AutoScaleDimensions assigns for four fullscreen forms

---

ShareX.HelpersLib/Controls/MyPictureBox.cs

Fixed the issue of #2933
There were two options:
1. Deep clone the image.
2. Disable the preview in the main window.
I choosed the second option because I think it's performance-wise better than the first option. Also, as the dedicated preview window is an dialog, the user can't interact with the main window, so there is no need for a preview.

Fixed issue #2933

---

ShareX.UploadersLib/FileUploaders/AmazonS3.cs
ShareX.UploadersLib/FileUploaders/AmazonS3Settings.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx

This mostly relevant when using [Origin Access Identity](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html)

Allow to disable setting public ACL on files uploaded via S3

---

ShareX.UploadersLib/Helpers/CustomUploaderItem.cs

`\$` is a thing now
`\\$` is a thing now
`\\` is a thing now
Truth table:
```java
\$  -> $
\\  -> \
\\$ -> \$
\X  -> X
```

Add escapes to ParseURL

---

ShareX.HelpersLib/Helpers/Helpers.cs
ShareX.HelpersLib/NameParser/CodeMenuEntryFilename.cs
ShareX.HelpersLib/NameParser/NameParser.cs
ShareX.HelpersLib/Properties/Resources.Designer.cs
ShareX.HelpersLib/Properties/Resources.es.resx
ShareX.HelpersLib/Properties/Resources.fr.resx
ShareX.HelpersLib/Properties/Resources.resx
ShareX/Forms/TaskSettingsForm.cs

This adds `%rf{path}` to Task > Upload > File Naming, which reads the file at `path` and uses a random line from it for the filename (Similar to `%radjective` and `%ranimal`)
https://suplex.me/EasyHariyama.png
If the file is not found/not able to be read/some other error, the preview will display the error message, but trying to upload will popup an error window
https://gfycat.com/BothZealousEstuarinecrocodile

Add %rf to use a random line from a file

---

ShareX.HistoryLib/HistoryItemManager.cs
ShareX.HistoryLib/HistoryItemManager_ContextMenu.cs
ShareX.HistoryLib/Properties/Resources.Designer.cs
ShareX.HistoryLib/Properties/Resources.resx

As mentioned in #3115, this adds three new copying options.
Tested and functional as intended.

Add new Markdown copying options (Fixes #3115)

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs
ShareX.sln.DotSettings

When uploading images with the direct link setting enabled, the link returned downloads the image instead of displaying it directly in the browser. This change will display the image/uploaded file in the browser instead.

Use preview link for OwnCloud/NextCloud file uploads

---

ShareX.HelpersLib/Properties/Resources.Designer.cs
ShareX.HelpersLib/Properties/Resources.de.resx
ShareX.HelpersLib/Properties/Resources.resx
ShareX.HelpersLib/UITypeEditors/WavFileNameEditor.cs

Added string resource + German translation for a missing string.
The wav file browser in question shows on `Task Settings -> Advanced -> CustomCaptureSoundPath -> [...]` for example.

Wav file browser doesn't show "Browse for executable" in title anymore

---

ShareX.ImageEffectsLib/Drawings/DrawImage.cs

Implements the suggestion of #3157.
`SizeMode` has the following values:
- `AutoSize`: size is determined by the image's size, the `Size` property does nothing
- `Absolute`: size is determined by the `Size` property, in pixels
- `Percent`: size is determined by the `Size` property, as a relative percentage of the image's size

Added Size and SizeMode properties to the image watermark effect

---

ShareX.ImageEffectsLib/Drawings/DrawImage.cs

Since #3158 was merged, opening a new one. (Don't think you can re-open a merged pull request?)
Differentiates `PercentageOfWatermark` and `PercentageOfCanvas` now, which can't be misunderstood I think.

[UPDATE] SizeMode relative values

---

ShareX.UploadersLib/FileUploaders/FTP.cs

According to https://github.com/robinrodricks/FluentFTP#file-transfer you need to call `GetReply()` after completing the transfer from `OpenRead()` or `OpenWrite()`
Without this fix I get consistently the problems as described on the discord server (half the image is not there) for large(ish) images. With this fix I get consistently zero issues.
couple notes:
1. I pulled a chuck of code in `UploadData` to its own method, since it appeared twice and it needed the fix in both, so it was easier to just put it like this. However I suck at creating good names of things, so if you dont like the name of that method, gimmy a better one ;) xd
2. I dont know for sure what the `ftpResult` thing will contain, but from what I can tell its the ftp server telling the client if the transfer was ok, so I …

add call to GetReply after using OpenRead or OpenWrite according to FluentFTP documentation

---

ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/UploadersConfig.cs

If user enters it, then save it.
Fixes #3186 (and linked issues)

Remove check of whether to save TinyPic login info

---

ShareX/Forms/AutoCaptureForm.cs
ShareX/TaskHelpers.cs

This change means that whether it's "Start auto capture using last region", or just opens the "Auto Capture" window, that any task settings overrides associated with the hotkey will be respected.
A use for this change is to be able to create screenshots for a timelapses while still using ShareX as normal. By overriding the capture path and after capture tasks, a user can have the auto captured images be in a separate directory and not be uploaded, without having to make those changes globally.

Respect Hotkey Overrides with Auto Capture

---

ShareX/Forms/ScreenRecordForm.cs
ShareX/Forms/TaskSettingsForm.Designer.cs
ShareX/Forms/TaskSettingsForm.cs
ShareX/Forms/TaskSettingsForm.resx
ShareX/Properties/Resources.Designer.cs
ShareX/Properties/Resources.resx
ShareX/TaskSettings.cs

This PR adds a lovely confirmation dialog when a recording is cancelled.
Also, allows the user to toggle this function.

Add Confirmation to Abort Recording - Fixes #3287

---

ShareX.HelpersLib/Helpers/URLHelpers.cs
ShareX.UploadersLib/BaseUploaders/Uploader.cs
ShareX.UploadersLib/FileUploaders/OneDrive.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs
ShareX.UploadersLib/Helpers/OAuth/OAuth2Info.cs
ShareX.UploadersLib/Helpers/OAuth/OAuth2ProofKey.cs
ShareX.UploadersLib/Helpers/ProgressManager.cs
ShareX.UploadersLib/ShareX.UploadersLib.csproj
ShareX.UploadersLib/UploadersConfig.cs

- Supports OneDrive Personal, OneDrive Business and SharePoint #1853
- Removes upload limit #1121
- Will reset old OneDrive settings
Requires new API key from [Application Registration Portal](https://apps.dev.microsoft.com):
- Application ID is the `ClientID`
- Generate Password to get the `ClientSecret`
- Put ShareX callback URL in Web App section (ignore Native App section)

Update OneDrive Uploader to Microsoft Graph API

---

ShareX/StartupManagers/GenericStartupManager.cs

This prevents the user falling in some cases where enabling startup again was impossible without manually creating the shortcut.

Allow to create startup shortcut even when startup is disabled via Task Manager

---

ShareX.HelpersLib/Colors/ColorPickerForm.Designer.cs
ShareX.HelpersLib/Colors/ColorPickerForm.resx
ShareX.HelpersLib/Controls/MyListView.cs
ShareX.HelpersLib/Controls/MyPictureBox.Designer.cs
ShareX.HelpersLib/Controls/MyPictureBox.cs
ShareX.HelpersLib/Controls/TabToListView.cs
ShareX.HelpersLib/Controls/TabToTreeView.cs
ShareX.HelpersLib/Controls/ToolStripButtonCounter.cs
ShareX.HelpersLib/Forms/InputBox.cs
ShareX.HelpersLib/Forms/InputBox.resx
ShareX.HistoryLib/HistoryForm.Designer.cs
ShareX.HistoryLib/HistoryForm.resx
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
ShareX/Forms/ActionsToolbarForm.cs
ShareX/app.config

Enables .NET 4.5 DPI fixes and fixes UI elements that were clipped or unusable at high DPI.
Before: https://imgur.com/a/WLh3y
After: https://imgur.com/a/bp8RQ
Should fix issues like #2672, #3249, #2635 etc.

Make ShareX more usable in high DPI monitors

---

ShareX.HelpersLib/Extensions/XMLExtensions.cs
ShareX.UploadersLib/FileUploaders/Puush.cs

Split function always return array. If you look at the source of it, it even guarantees it with code contracts

Remove unnecessary null check

---

ShareX.ScreenCaptureLib/Shapes/Drawing/LineDrawingShape.cs

newPoints is array of structs "System.Drawing.Point". Any element of an array can not be null. That expression (newPoints[i] == null) always return false. So, we can remove this cycle without changes in program logic.

Cleanup code

---

ShareX.UploadersLib/FileUploaders/AzureStorage.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Addresses #2710, #2845, and #3144 with a variety of changes.
1) Support masking container name when using a custom domain.
2) Return paths without $root in the URL.
3) Allow for custom upload paths like S3.

Azure Storage Updates

---

ShareX/Forms/MainForm.de.resx
ShareX/Forms/TaskSettingsForm.de.resx

Rename “Bildschirmfarbenauswähler” in all strings of German translations to “Bildschirmfarbauswähler” to clarify that you only pick one color at a time and not multiple ones.

Small change in translated word in German

---

ShareX.UploadersLib/FileUploaders/Pomf.cs

Since edfile.pro will be switching the upload end-point to https://edfile.pro/api/upload, it is appropriate to reflect those changes here.

Updated edfile.pro upload end-point.

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Added the ability to auto expire shared links after a certain amount of days.
Uses the expireDate paramaeter from OwnCloud/NextCloud OCS share API as described [here](https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-share-api.html#create-a-new-share)

Auto expiring of shared links for OwnCloud/NextCloud

---

ShareX.HelpersLib/Helpers/Helpers.cs
ShareX.HelpersLib/Helpers/MathHelpers.cs

`MathHelpers.CryptoRandom()` uses a PRNG that returns high-quality random numbers. This PR makes randomly generated file names (like `5vnQUQ.png`) more unique, more collision resistant, and less guessable (`System.Random()` is seeded with the system time, I think via [`Environment.TickCount`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.tickcount?view=netframework-4.7.2)). 
Some uploader targets (e.g. B2) are able to upload the same file to the same path as a new "revision" or "version", so it is important to make sure that randomly named files will be sufficiently unique.

 MathHelpers: add CryptoRandom()

---

ShareX.ScreenCaptureLib/Screencast/FFmpegHelper.cs
ShareX.ScreenCaptureLib/Screencast/ScreenRecorder.cs
ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs
ShareX/Forms/TaskSettingsForm.Designer.cs
ShareX/Forms/TaskSettingsForm.cs
ShareX/Forms/TaskSettingsForm.resx
ShareX/ScreenRecordManager.cs
ShareX/TaskSettings.cs

Added option to record with lossless encoding and then after recording is complete using user configured encoding options to encode second time. This way user can select slow encoding preset and be able to get lower file size without affecting screen recording performance. Fixes issue #2265.

fixes #2265: Added two pass encoding option

---

ShareX/ApplicationConfig.cs
ShareX/Forms/MainForm.cs

ShareX will remember column widths of main window task list, that way user can customize column widths to their preference. Fixes #2635.

fixes #2635: Save column widths of task list view

---

ShareX.HelpersLib/Forms/ImageViewer.cs

On multiple monitors it was a problem, that the ImageViewer would always use the default monitor and not the current monitor.

Use current screen location for ImageViewer

---

ShareX.HelpersLib/Resources/animals.txt

Spacing on some names would cause URLs to add %C2%A0 on the end of them. Removing these spaces fixes it.
For example: https://linusdrop.tips/DentalSkinnyPikeperch%C2%A0
In the original file, "pikeperch" has a blank icon after the name and this causes the "%C2%A0" in the URL.

Fixed spacing on some names

---

ShareX.HelpersLib/Enums.cs
ShareX.HelpersLib/Forms/ClipboardContentViewer.cs
ShareX/UploadManager.cs

Fixes #1769.
Clipboard content displayed in ClipboardContentViewer is now cached with it's type. It allows clipboard to be freely used, while ClipboardContentViewer form is opened. When "OK" button is pressed, cached content is uploaded.

Fixes unexpected clipboard content viewer behavior 

---

ShareX/Program.cs

Improves debug logging to indicate if ShareX is running as an elevated process

Indicate in debug logs if ShareX is running as an elevated process

---

ShareX/Forms/MainForm.cs

`operator int` enforces checked semantics but `operator long` does not

Make code prettier

---

ShareX.UploadersLib/Forms/OCRSpaceForm.Designer.cs
ShareX.UploadersLib/Forms/OCRSpaceForm.cs
ShareX/ApplicationConfig.cs
ShareX/Forms/TaskSettingsForm.Designer.cs
ShareX/Forms/TaskSettingsForm.cs
ShareX/Forms/TaskSettingsForm.resx
ShareX/Properties/Resources.Designer.cs
ShareX/Properties/Resources.resx
ShareX/TaskHelpers.cs
ShareX/TaskSettings.cs
ShareX/UploadInfoManager.cs
ShareX/WorkerTask.cs

To improve the OCR experience and to tackle the tickets mentioned previously, some new settings and modes have been added to the OCR tool.
**New Settings**
Introduces a "silent" operation mode and default language selection.
I have also tested and confirmed the custom hotkey settings can be applied to the OCR task.
**UI Change**
The text box has been made read only as users should not be modifying the text.

 Add new settings to OCR and enhancements - Fixes #3712, #3601, #2848

---

ShareX.HelpersLib/Forms/HashCheckForm.Designer.cs
ShareX.HelpersLib/Forms/HashCheckForm.cs

Regarding the UI bug, the progress bar is not being reset to 0% when a file hash is being calculated causing the bar to jump from 100% down to whatever percentage the file is at, not start from 0%.

Allow hash result to be selected via Ctrl-A (Fixes #3792) and fix UI bug with progress bar

---

ShareX.HelpersLib/ConvolutionMatrix.cs
ShareX.HelpersLib/ConvolutionMatrixManager.cs
ShareX.HelpersLib/Extensions/NumberExtensions.cs
ShareX.HelpersLib/Helpers/MathHelpers.cs
ShareX.HelpersLib/ShareX.HelpersLib.csproj
ShareX.ImageEffectsLib/Filters/GaussianBlur.cs
ShareX.ImageEffectsLib/Filters/MatrixConvolution.cs
ShareX.ImageEffectsLib/ShareX.ImageEffectsLib.csproj

This allows the user to customize the sigma and kernel size, as well as uses a two-pass algorithm to increase performance.
The matrix convolution code has been rewritten to support this change, but all existing effects based on matrix convolution are left unchanged (minus basic changes for the rewrite) and working.

Add user customizable gaussian blur

---

ShareX.ScreenCaptureLib/Forms/WebpageCaptureForm.Designer.cs
ShareX.ScreenCaptureLib/Forms/WebpageCaptureForm.cs
ShareX.ScreenCaptureLib/Forms/WebpageCaptureForm.resx
ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj
ShareX.ScreenCaptureLib/WebpageCapture/EdgeWebpageCapture.cs
ShareX.ScreenCaptureLib/WebpageCapture/InternetExplorerWebpageCapture.cs
ShareX.ScreenCaptureLib/WebpageCapture/WebpageCaptureBase.cs
ShareX.ScreenCaptureLib/WebpageCapture/WebpageCaptureOptions.cs
ShareX/ApplicationConfig.cs
ShareX/ShareX.csproj

This allows, on machines that run the April 2018 update or higher, to take screenshots of websites that don't work anymore on IE. (Fixes #3634)

Add support for Edge webview in website capture

---

ShareX.UploadersLib/FileUploaders/Pushbullet.cs

Adds information about filetype to push. Pushbullet on android can then open the Image/File easily, and also shows a preview for images. Text can now be opened, but is currently sent as a textfile instead of actual text. Should we maybe change that too?
#3771

Pushbullet upgrade

---

ShareX.UploadersLib/FileUploaders/OwnCloud.cs

See issue: https://github.com/ShareX/ShareX/issues/3868
Not adding either /preview or /download to URL generates links that show a preview of a file. /preview only works for images (showing literally only the image in the browser). This change makes sure the logic is right.
Note: The logic is right so it should work. But I'm not sure if the syntax is right.

Don't generate direct download links when PreviewLink is checked

---

ShareX.UploadersLib/ImageUploaders/GooglePhotos.cs

Album list will become polluted with redundant single album share images, we can assume that no shared albums other than ones used for public links will be made.
This will not fix long pagination responses due to many shared albums.

Fix album list pollution

---

ShareX.UploadersLib/ImageUploaders/GooglePhotos.cs

Pagination failed if the albums response is empty, but a pagination token still exists.

Fix empty albums list

---

ShareX/ShareX.csproj

Avoids potential version conflicts if a newer SDK is installed

Version-lock Windows.winmd assembly reference

---

ShareX.HelpersLib/DNS/DNSChangerForm.cs

Norton ConnectSafe has been discontinued recently. https://connectsafe.norton.com/
This PR replaces it with CleanBrowsing.

Replaced Norton ConnectSafe with CleanBrowsing as it was discontinued.

---

ShareX.ScreenCaptureLib/Enums.cs
ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.Designer.cs
ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.cs
ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.resx
ShareX.ScreenCaptureLib/Screencast/FFmpegOptions.cs
ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs

Intel QuickSync provides hardware H.264 encoding on Intel Sandy Bridge CPUs and up and hardware H.265 encoding on Skylake CPUs and up via a dedicated die on the processor chip, being faster than CPU encoding and more power efficient than GPU encoding

Add support for Intel QuickSync

---

ShareX.HelpersLib/Properties/Resources.ru.resx

Current version of translation, albeit more compact, makes it impossible to distinguish between file, image and text uploaders in the list of uploaders in Task Settings -> Upload -> Uploader Filters. This pull fixes that.

Fixing Russian translation

---

ShareX.HelpersLib/ConvolutionMatrix.cs
ShareX.HelpersLib/ConvolutionMatrixManager.cs
ShareX.ImageEffectsLib/Filters/GaussianBlur.cs

This increases performance massively when applying matrices on high resolution images: doing a Gaussian blur with size 3 on a 6550x4371 image reduced processing time from 41 seconds to 22 seconds on my dual core laptop CPU, probably even more on quad, hexa or octo core.
The second changes fixes blur being unexpectedly cut off on the normal image frame instead of extending over it when you had a strong blur effect on an image which included alpha:

Parallelize matrix convolution and consider transparency in gaussian blurs

---

ShareX.ScreenCaptureLib/RegionCaptureOptions.cs
ShareX.ScreenCaptureLib/Shapes/BaseShape.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

This is the follow up PR of #4058 where the select tool was added. This PR is supposed to fix: 
**Tested Scenarios:**
1.  _with switch to select tool option active_: Fully use crop tool -> Cropping not cancelled while drawing region 
2. _with switch to select tool option active_: Cancel crop tool -> Crop selection is removed when switching to any other tool. 
3. Switching to matching shape tool after selection of a shape with select tool -> Selection is kept
4. Switching to another shape tool after selection of a shape with select tool -> Selection is cleared
5. Switching to another shape tool after selection of a shape with matching tool  -> Selection is cleared
6. Selecting different shape types (resizable/not-resizable) -> resize nodes are properly cleared. 
7. _with switch to select …

Fix issues for select tool

---

ShareX/Program.cs

It's just a simple change to catch all exceptions in program because when this is missed, sometimes exceptions are not catched properly. 
[StackOverFlow Post about this](https://stackoverflow.com/questions/5762526/how-can-i-make-something-that-catches-all-unhandled-exceptions-in-a-winforms-a)

catching all Exceptions!

---

ShareX.HelpersLib/Helpers/ImageHelpers.cs

Hi there!
I'm a developer at PVS-Studio company. Recently, I have checked your project with our static code analyzer and found one interesting bug: pixelization doesn't work for png images which have some degree of transparency. This pull request is aiming to solve that issue.
We actually dedicated half of our article to your project check and described more minor imperfect places. You can read it [here](https://www.viva64.com/en/b/0670/), there is a detailed explanation of that pixelization bug too.
We are glad to give you our license for one month, so you can test your project more thorough:
Name: ShareX
Key: 94AG-4M9U-1KK0-T18E
License Type: Team9 License up to 9 developers
License Valid Thru: Oct 17, 2019

Fixed problem with pixelization for png images

---

ShareX/Forms/QRCodeForm.cs

Minor testing and I wasn't able to break it, unsure how it bypasses the Pre-Configured region option.
Mainly wrote this to respect the user's task setting of using a Square or Circle magnification shape

Use Default Task Settings for screen QR scanner

---

ShareX.HelpersLib/Controls/BlackStyle/BlackStyleCheckBox.cs
ShareX/Controls/TaskThumbnailPanel.Designer.cs
ShareX/Controls/TaskThumbnailPanel.cs
ShareX/Controls/TaskThumbnailView.Designer.cs
ShareX/Controls/TaskThumbnailView.cs
ShareX/Forms/MainForm.cs
ShareX/UploadInfoManager.cs

Allows selecting multiple thumbnail panels with <kbd>Ctrl</kbd> key. Also shows selected indicator at top left corner of panels.
Video: https://jaex.getsharex.com/2019/10/HfL2DXaMii.mp4

fixed #4280: Thumbnail view multi select support

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs

Whenever you move your mouse quickly around the shapes on the screen there are usually some visual glitches as the FromRectangle value is always set to PreviousHoverRectangle. This simple change smoothens those animations and improves the overall user experience. Simply use the last CurrentRectangle as the new FromRectangle value.
Preview before/after: https://i.imgur.com/WI0Gof7.mp4

Smoothened regionAnimation rectangle animation

---

ShareX.HelpersLib/Forms/DebugForm.de.resx

The current translation could be misunderstanding since it more likely means to open the "upload protocol" and not to upload the protocol. 
This commit clarifies the "upload" of the protocol so the following popup about sensitive information actually makes sense.

Update german translation for uploading log files in the debug protocol

---

ShareX.HelpersLib/Native/NativeEnums.cs
ShareX.HelpersLib/Native/NativeMethods_Helpers.cs

I'm not quite sure which exact Windows 10 build changed the API, but build 18985 is the earliest I know of which did.

Fix dark titlebar for Windows 10 20H1

---

ShareX.HistoryLib/HistoryItemManager.cs
ShareX.HistoryLib/HistoryItemManager_ContextMenu.cs

This fulfills the request to implement the ability to mass copy links when multiple items are selected in the 'history' area https://github.com/ShareX/ShareX/issues/2292.

Added the ability to mass copy links in different formats

---

ShareX.HelpersLib/ApplicationInstanceManager.cs
ShareX.HelpersLib/Cryptographic/HashCheck.cs
ShareX.HelpersLib/Cryptographic/Translator.cs
ShareX.HelpersLib/Enums.cs
ShareX/ShareX.csproj
ShareX/TaskHelpers.cs
ShareX/TaskSettings.cs

This is a step towards full .NET Core API coverage. It makes ShareX.HelpersLib 100% covered by .NET Core + Platform Extensions, from a 99.41% previously
Before: 
After:

Replace System.Remoting by named pipe, remove RIPEMD-160 support

---

ShareX.UploadersLib/FileUploaders/Seafile.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Now ShareX create link for SeaFile uploader which lead to SeaFile page.
The problem that if the image is larger than the available space on the SeaFile page than the image is shrunk. There is no ability to view it in full size without downloading first, what is inconvenient.
But there is the ability to create a direct link by adding "raw=1" parameter for the url.
Example:
"http://example.com/f/af416996a8064ada9c7c/" - leads to SeaFile page.
"http://example.com/f/af416996a8064ada9c7c/?raw=1" - leads to file directly.
I added a checkbox called "Direct URL" to the SeaFile uploader configuration so that the parameter "raw" is added to the address. 
Now it is possible to get direct link right after uploading.

Added check box to make direct URL for SeaFile uploader

---

ShareX.UploadersLib/Enums.cs
ShareX.UploadersLib/FileUploaders/Box.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/UploadersConfig.cs

Adds a dropdown box to the Box file uploader settings under the "Create shareable link" checkbox.
This has been tested with all 3 access levels and I saw each successfully upload with the correct share link setting in the Box web interface.
See Box API for reference about access levels: https://developer.box.com/guides/shared-links/create/
**Please note** the "collaboration" access level in the Box docs should actually be "collaborators" as seen in their own API implementations (e.g. https://github.com/box/box-node-sdk/blob/b06f4041d54fb2b102603edd2624876d25500e9a/lib/box-client.js#L392).
I have tested and made sure I to add the correct "collaborators" value.

Allow "access level" selection for Box shareable link

---

ShareX/Forms/ScreenRecordForm.zh-TW.resx

Abort (中止) and Stop (停止) have different meaning, Correct the transaction to distinguish the two.
Due to this transaction problem, there is currently no way to distinguish between abort and stop in screen recoding.
Only the Traditional Chinese version has this problem and Simplified Chinese version dose not.

Abort (中止) and Stop (停止) have different meaning

---

ShareX.IndexerLib/IndexerHtml.cs
ShareX.IndexerLib/IndexerSettings.cs

Added an additional feaature to the Directory Indexer module. There are now two settings to show the full path of the directories, or the shorter variation of the path starting from the root. Another update is to show number seperators on the folder and file count for clarity.
Notes in the picture:
Marker 1 - original root folder path.
Marker 2 - original sub folder path.
Marker 3 - original file/folder count.
Marker 4 - updated full folder path for root and sub folders.
Marker 5 - updated file/folder count with seperators.
Marker 6 - updated folder path limiting to the selected root folder.

Added display path options to folder listing module.

---

ShareX.ScreenCaptureLib/RegionCaptureTasks.cs

When the ruler tool is opened, the region info window is hidden when the region is too thin, making the ruler useless for straight lines or accurate measurements.
This is a one line fix so the ruler is always displayed.
Marker 1 - Test area
Marker 2 - Start position
Marker 3 - End position - No Information shown.
Marker 4 & 5 - Increase region size to display limit now shows the ruler information.
Marker 6: - Pull request fix to show the info window at any region size.

Fixed ruler disappearing when the region box is too small.

---

ShareX.UploadersLib/FileUploaders/Pushbullet.cs
ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs

This fixes Pushbullet from getting and storing empty devices when pulling from the user's account. Sorry, this was an oversight on my part when the feature was implemented.

Fix storing invalid/deleted pushbullet devices

---

ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.Designer.cs
ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.cs
ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.resx
ShareX.ScreenCaptureLib/Screencast/FFmpegOptions.cs
ShareX.ScreenCaptureLib/Screencast/ScreenRecorder.cs

Adds a combobox allowing users to alter bayer_scale that is used when encoding a gif file with the bayer dithering mode.
The UI for it isn't that great, as in the label doesn't exist, however the Screen Recording menu is pretty packed as is, I have only put an indication of it's function within the tooltip regrettably.
There's a little bit of the bayer_scale in action on [this article](http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html#usage), otherwise it is covered in the [ffmpeg filters documentation](https://ffmpeg.org/ffmpeg-filters.html#paletteuse)

Bayer Scale can be changed for gifs if Bayer dither is in use

---

ShareX.HelpersLib/Cryptographic/HashCheck.cs
ShareX.HelpersLib/Helpers/ImageHelpers.cs
ShareX.ImageEffectsLib/Filters/ColorDepth.cs
ShareX.ImageEffectsLib/Forms/ImageEffectsForm.cs
ShareX.ImageEffectsLib/ShareX.ImageEffectsLib.csproj
ShareX.MediaLib/Forms/VideoConverterForm.cs
ShareX/ShareX.csproj

Added "Color depth" filter that remaps RGB pixel color to the nearest color at the specified color depth. For example, #E1CB96 will be remapped to #DDCC99 when "BitsPerChannel" is set to 4.
The attached image includes three sample images, each processed by the filter using the range of allowed bpc values (1-8).

Added "Color depth" filter

---

ShareX.HelpersLib/NameParser/CodeMenuEntryPixelInfo.cs

Basically what the title says, you can now use capital letters `$R`, `$G`, and `$B` to get a color string with colors represented from 0-1. This format of colors is used with a number of things, most notably Unity, and this will save me and hopefully others from having to convert normal colors to 0-1 range every so often, which I say is a win.    
I have it set to round to 3 decimal places, but that's totally arbitrary and any precision will basically work, although some level of rounding seems sensible otherwise you get unnecessarily long outputs. If you think it should be more/less precise, just LMK and I'll do whatever. Also, I think the use of `1.000` in the description strings gets the point across pretty well, but that can also be stated more clearly if need be. 
I looked around for …

Update color picker format options to include 0-1 colors

---

ShareX/Forms/HotkeySettingsForm.cs

If two hotkeys sharing same keybinds then changing one hotkey will register other failed hotkey automatically.
Example:

fixed #5068: Automatically register failed hotkeys

---

ShareX.HelpersLib/Forms/ColorPickerForm.cs
ShareX.HelpersLib/Helpers/ColorHelpers.cs
ShareX.HelpersLib/NameParser/CodeMenuEntryPixelInfo.cs
ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/RegionCaptureOptions.cs
ShareX.ScreenCaptureLib/RegionCaptureTasks.cs
ShareX/Forms/TaskSettingsForm.Designer.cs
ShareX/Forms/TaskSettingsForm.cs
ShareX/Forms/TaskSettingsForm.resx
ShareX/TaskHelpers.cs
ShareX/TaskSettings.cs

Added option to allow customizing screen color picker info text near cursor. That way for example color name info can be added.
Default syntax is: `RGB: $r, $g, $b$nHex: $HEX$nX: $x Y: $y`
Example screenshot with color name info added:

fixed #5059: Added screen color picker info text option

---

ShareX/Forms/ScreenRecordForm.cs
ShareX/TaskHelpers.cs

Now screen record encoding progress percentage is visible in tray icon. That way user can know status of encoding.
Example screenshot:

fixed #5020: Show screen record encoding progress in tray icon

---

ShareX.HelpersLib/Enums.cs
ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs
ShareX.ScreenCaptureLib/Properties/Resources.resx
ShareX.ScreenCaptureLib/Shapes/AnnotationOptions.cs
ShareX.ScreenCaptureLib/Shapes/Drawing/ArrowDrawingShape.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs

Adds a shape option for drawing arrows pointing to their origin
Closes #5103

Allow drawing arrows in reverse

---

ShareX/Forms/TaskSettingsForm.Designer.cs
ShareX/Forms/TaskSettingsForm.cs
ShareX/Forms/TaskSettingsForm.resx
ShareX/TaskHelpers.cs
ShareX/TaskSettings.cs

Added entry for alternative screen color picker format to Task Settings -> Tools. As per request #4743 .
If holding SHIFT when you copy color info in screen color picker, alternative format is copied instead.

Added alternative screen color picker format.

---

ShareX.ImageEffectsLib/Manipulations/Canvas.cs

Currently, adding a border to the canvas requires absolute pixel units.
This PR allows you to add border based off a percentage of the canvas size, allowing you to make borders that scale well to different image sizes, especially for high resolution/dpi displays.

Add canvas margin from percentage canvas size

---

ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs

Make sure the menu position is set when "Remember menu state" is enabled.

Fix "Remember menu state" + "Lock menu" issue.

---

ShareX.UploadersLib/FileUploaders/Plik.cs

This adds encoding to the result URL so that it can be pasted in chats and so on without having to replace space with %20 and so on.

Fixed URL encoding for Plik

---

ShareX.HelpersLib/FileDownloader.cs

The following exception is raised when the program attemps to extract the ffmpeg archive:
`System.IO.IOException: The process cannot access the file 'C:\Users\ ... \AppData\Local\Temp\ShareX\ffmpeg.zip' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
at …

ffmpeg zip archive extraction fix

---

ShareX/Forms/NotificationForm.cs

Title says all, here's a quick demonstration:
https://user-images.githubusercontent.com/22963120/116364414-b32e9c80-a7f3-11eb-8eeb-e464da939f42.mp4

Add drag drop support for notifications with file name

---

ShareX.UploadersLib/FileUploaders/OneDrive.cs

Should fix #5375 and #5553. I'd appreciate testing from OneDrive for Business users.
According to MS, OneDrive links require the "scope" parameter now: https://github.com/OneDrive/onedrive-api-docs/issues/1435#issuecomment-834566293

Fix error with OneDrive for Business sharable links

---

ShareX.HelpersLib/ColorPickerOptions.cs
ShareX.HelpersLib/Controls/ColorButton.cs
ShareX.HelpersLib/Forms/ColorPickerForm.cs
ShareX.HelpersLib/ShareX.HelpersLib.csproj
ShareX.ScreenCaptureLib/Forms/NewImageForm.cs
ShareX.ScreenCaptureLib/Forms/TextDrawingInputBox.cs
ShareX.ScreenCaptureLib/RegionCaptureOptions.cs
ShareX.ScreenCaptureLib/RegionCaptureTasks.cs
ShareX.ScreenCaptureLib/Shapes/Drawing/TextDrawingShape.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
ShareX/TaskHelpers.cs

Color palette selection will be saved now:
That way user don't have to select "Standard colors" each time color picker is opened.

fixed #4132: Remember color picker color palette mode selection

---

ShareX/Forms/MainForm.cs
ShareX/Program.cs

ShareX first checks `HKEY_LOCAL_MACHINE\SOFTWARE\ShareX` and if it not exists then checks `HKEY_CURRENT_USER\SOFTWARE\ShareX` registry key, so HKLM have priority over HKCU. If `DisableUpdateCheck` string with `true` value is found then ShareX disables auto update checking.

fixed #4219: Added registry check to allow system admins to disable update check

---

ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

Swap resize key with move key in region capture so arrow keys moves shapes instead of resize.
Keybinds after change:
<kbd>Arrow keys</kbd> = Move cursor / Move current shape
<kbd>Ctrl + Arrow keys</kbd> = Resize current shape from bottom right corner
<kbd>Alt + Arrow keys</kbd> = Resize current shape from top left corner
<kbd>Shift + Arrow keys</kbd> = Resize or move faster

fixed #4669: Swap move/resize hotkeys in region capture so arrow keys moves shapes instead of resize

---

ShareX.HelpersLib/Printer/PrintHelper.cs
ShareX.HelpersLib/Printer/PrintSettings.cs
ShareX/Forms/ApplicationSettingsForm.Designer.cs
ShareX/Forms/ApplicationSettingsForm.cs
ShareX/Forms/ApplicationSettingsForm.resx

Add a way for users to, if `Don't show Windows print dialog` is enabled, set a custom default printer for ShareX to use when printing.
This is mostly a quick and easy way to solve #674 but obviously also has a number of other applications. I tried to stick to the existing code style as much as possible.

Add Default Printer Override

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs

FPS limit would save, but not take effect on new capture until bumped

Fix FPS limit not applying preference

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
ShareX.ScreenCaptureLib/RegionHelpers/ImageEditorScrollbar.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs

This is a fix for [the issue Jaex reported](https://github.com/ShareX/ShareX/pull/6108#issuecomment-1046174097) after the floating point merge.
Minor refactor.  The only routine that updates CanvasCenterOffset now is PanToOffset (replacing AutomaticPan), and this only updates the offset if a pan actually occurred (i.e. the pan wasn't constrained because we're at the pan limit).

Fix panning regression (panning at limit accumulates invisible changes)

---

ShareX/Forms/InspectWindowForm.Designer.cs
ShareX/Forms/InspectWindowForm.cs
ShareX/Forms/InspectWindowForm.resx

This adds a "Pin to Top" button to the "Inspect Window" tool.
When pressed, the button will set the currently inspecting window as
"HWND_TOPMOST" (or "HWND_NOTOPMOST" if it was already TOPMOST)
This has the effect of the window always staying in front of other windows, which is just a useful utility tool
which i thought would best fit into Inspect Window.
This is my first pull request to ShareX and i wasn't able to find commit guidelines anywhere, so please review this pull
and LMK if i i'm doing something wrong ^^

Add Pin to Top button to Inspect Window tool

---

ShareX/Forms/TaskSettingsForm.zh-CN.resx

for "ScreenRecorder", it's More accurate to use "屏幕录制" than “屏幕记录”

Update Chinese String of “ScreenRecorder”

---

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs

Move "IsImageModified = false" 
from 
ReceiveImageForTask
to 
OnSaveImageRequested success
and
OnSaveImageAsRequested success

fix #6222 ( set IsImageModified to false only on Save and SaveAs OK )

---

ShareX.HelpersLib/Helpers/URLHelpers.cs
ShareX.UploadersLib/FileUploaders/AmazonS3.cs

Hosting a local version of an S3 compatible service like MinIO doesn't require https, but the uploader forces https no matter what. If the user specifies that it should be uploaded with http then it should use http.
Related issue #6228

Change url prefix addition in S3 uploader

---

ShareX/ShareX.csproj

It seems that ResX missed one EmbeddedResource responsible for translating the main application screen. Sorry for the confusion.

Fix missing EmbeddedResource in PL translations

---

ShareX.HelpersLib/Settings/SettingsBase.cs

On Windows file shares (DFS) with restricted WRITE_DAC permission, the method File.Replace results in a System.UnauthorizedAccessException, even when the user has full permissions to interact with the file and folder. This configuration can commonly be found in business environments.
By setting the flag ignoreMetadataErrors to true, errors related to attributes and ACL are ignored. This results in the settings being saved correctly. Normal errors during file operation are not suppressed with this change, they should fail as usual. Attributes and permissions should not be affected either as long as the permission to set them is present. 
Reference: https://stackoverflow.com/questions/59062659/file-replace-doesnt-work-on-shared-driver
Example of the error:
```
2022-07-12 08:54:13.531 - …
```

Ensure proper saving of settings on file shares

---

ShareX.MediaLib/Forms/VideoConverterForm.resx

- widen the form by 102 pixels
- widen and move some elements accordingly
- change the default text for lower/higher video quality to represent real world line lengths in the form designer
Before (Romanian):
After (Romanian):
Before (English):
After (English):
Designer:

Widen Video Converter Form to fit translated lines

---

ShareX.ScreenCaptureLib/RegionHelpers/ResizeNode.cs

When resizing an element I could observe resize nodes glitching out a bit

Make resize nodes more stable

---

ShareX.HelpersLib/Enums.cs
ShareX.HelpersLib/Helpers/ImageHelpers.cs
ShareX.HelpersLib/Properties/Resources.Designer.cs
ShareX.HelpersLib/Properties/Resources.resx
ShareX.ImageEffectsLib/Filters/TornEdge.cs
ShareX.ImageEffectsLib/Filters/WaveEdge.cs
ShareX.ImageEffectsLib/Forms/ImageEffectsForm.cs
ShareX.ImageEffectsLib/ShareX.ImageEffectsLib.csproj
ShareX.ScreenCaptureLib/Enums.cs
ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs
ShareX.ScreenCaptureLib/Properties/Resources.resx
ShareX.ScreenCaptureLib/Shapes/AnnotationOptions.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
ShareX.ScreenCaptureLib/Shapes/Tool/CutOutTool.cs
ShareX.ScreenCaptureLib/Shapes/Tool/TrimInteriorTool.cs
ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj

Implement #4513 by adding a tool to "cut out" the middle parts of images.
Example of the result:
Feature checklist:
- - [x] Zig-zag (sawtooth)
- - [x] Wave 
- - [x] Torn edge
- - [x] ~~Gradient crossfade~~ (dropped)
Handling of outline or background on the cut out effects might be better left for the user to do with Image Effects or external tools. There are some UI issues with making clear that the cut-out effect area is transparent, but implementing edge effects on this would also be excessively much work, and giving a way to fill the cut out effect similarly has some bad UI affordances.
Giving an option to fill or outline the cut out effect would either use the image effects as-is, which could affect other transparent areas on the image, contrary to what the user might expect, or it …

Add Cut Out tool

---

ShareX.HelpersLib/Helpers/ImageHelpers.cs

The results from these fixes aren't always the most pretty either, but at least it should solve the glitches with floating islands in Torn Edges, and islands and bite marks in the Wave Edges.
Wave Edges gives poor results when the depth is more than half the width, there isn't much way around that.
Reported in https://github.com/ShareX/ShareX/pull/6454#issuecomment-1220919655

Fix corner glitches in edge effects

---

ShareX.HelpersLib/Controls/BlackStyle/BlackStyleLabel.cs
ShareX/Controls/TaskThumbnailPanel.Designer.cs
ShareX/Controls/TaskThumbnailPanel.cs
ShareX/Controls/TaskThumbnailPanel.resx

Allow quickly combining images from main window by dragging thumbnails:
Dragging to top combines images horizontally, dragging to bottom combines vertically.
Also users can drag image file from Windows Explorer to thumbnail.

Quick image combine with drag & drop

---

ShareX/Tools/OCR/OCRForm.Designer.cs
ShareX/Tools/OCR/OCRForm.cs

Allow closing OCR form with <kbd>Esc</kbd> key.
Fixes issue #6494.

fixed #6494: Allow closing OCR form with Esc key

---

ShareX.HelpersLib/Forms/HashCheckForm.Designer.cs
ShareX.HelpersLib/Forms/HashCheckForm.cs
ShareX.HelpersLib/Forms/HashCheckForm.resx

Allow dragging file from Windows Explorer to second "File path" textbox in "Hash check" window:
Fixes issue #6434.

fixed #6434: Allow dragging file to second file path textbox

---

ShareX.HelpersLib/Helpers/ImageHelpers.cs
ShareX.MediaLib/Forms/ImageCombinerForm.Designer.cs
ShareX.MediaLib/Forms/ImageCombinerForm.cs
ShareX.MediaLib/Forms/ImageCombinerForm.resx
ShareX.MediaLib/ImageCombinerOptions.cs
ShareX/TaskHelpers.cs

Added "Wrap after" option to "Image combiner" tool:
**Examples:**
Wrap after: `2`
Wrap after: `4`
Wrap after: `6`
Also added image count:
Fixes issue #6543.

fixed #6543: Added "Wrap after" option to "Image combiner" tool

---

ShareX.HistoryLib/Forms/HistoryForm.ja-JP.resx
ShareX.HistoryLib/Properties/Resources.ja-JP.resx
ShareX/Forms/TaskSettingsForm.ja-JP.resx

A scroll bar appeared. Reduce long strings:

Update Japanese translations : Adjust

---

ShareX.UploadersLib/FileUploaders/AzureStorage.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs
ShareX.UploadersLib/UploadersConfig.cs

The documentation covering this isn't straightforward on azure docs, but I gave it a shot anyway.
We can't apply cache-control to an entire storage container, so we have to do these per file, therefore putting it as a part of the upload process is necessary unless you want to do this through a separate rest request/azure cli
Adds a text box to the uploader config for users to specify their header
These are implemented directly onto the blob

Add Cache Control settings to Azure Uploader

---

ShareX/Forms/TaskSettingsForm.cs

Helps with #5838
before:
after:

Drop %t and %pn from clipboard upload name pattern preview

---

ShareX.UploadersLib/FileUploaders/OneDrive.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.cs
ShareX.UploadersLib/Forms/UploadersConfigForm.es-MX.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.fa-IR.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.fr.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.he-IL.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.id-ID.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.it-IT.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.ja-JP.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.ko-KR.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.nl-NL.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.pl.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.pt-BR.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.pt-PT.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.ru.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.tr.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.uk.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.vi-VN.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.zh-CN.resx
ShareX.UploadersLib/Forms/UploadersConfigForm.zh-TW.resx
ShareX.UploadersLib/UploadersConfig.cs

I have added the ability to generate direct links for OneDrive (using OneDrive's "Embed" feature). I noticed that there is an implementation for embedding in the source code for OneDrive, but it seems that this is not being called. Therefore, this pull request introduces a new switch to control it.
Additionally, after adding the switch control and relocating it, I observed that there have been numerous changes in ShareX.UploadersLib/Forms/UploadersConfigForm.resx. I'm not sure if this is normal. :D
Its translation is entirely based on other similar switch options.

OneDrive Add Use Direct Link

---

ShareX.ScreenCaptureLib/ImageEditorHistory.cs
ShareX.ScreenCaptureLib/ImageEditorMemento.cs
ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs
ShareX.ScreenCaptureLib/Properties/Resources.pt-BR.resx
ShareX.ScreenCaptureLib/Properties/Resources.resx
ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj

I have reworked the existing implementation of the undo (CTRL+Z) funtion and implemented a redo (CTRL+Y) one.
First I created the ImageEditorMemento class to store a state of the Image being edited, by keeping  the list of shapes drawn and the Bitmap canvas. I decided to have a constructor with only Shapes in order to avoid cloning and storing the whole Image all the time.
Next I added two stacks of this ImageEditorMemento class in to the shape manager to keep all the past states of the editor and the undone ones.
Then I have created two methods that create and stack the current state of the editor. One will store just the Shapes list and the other will store both the Shapes and the canvas.
Finally I have added the Undo and Redo methods, that will unstack the past state or the undone …

Implemented Undo/redo function on image editory

---

ShareX.HelpersLib/Properties/Resources.pl.resx

Renamed "Google image search" to "Google Lens" in Polish translations.

Update Polish translations

---

ShareX.UploadersLib/ImageUploaders/ImageShackUploader.cs

closes #7381 
URLs for images uploaded to ImageShack are currently poorly formatted to use `http` and the incorrect domain (`imageshack.com` rather than `imagizer.imageshack.com`), which results in unnecessary rewrites.
This fixes that so the URLs are formatted such that no rewrites are required.

fix/7381 updating ImageShack urls to use correct format and https

---

ShareX.HistoryLib/HistoryManagerSQLite.cs

Previously, opening a SQLite database stored on a network share via a UNC path
e.g. `\\server\share\file.db`) would fail with `unable to open database file`
This change uses .NET’s connection string parsing to correctly handle UNC paths,
ensuring databases on network shares can be opened without errors.
The previous failure of parsing lies in `System.Data.Sqlite`. SnapX does not have this bug because it uses Microsoft's `Microsoft.Data.Sqlite`, which has never had this exact bug, while the bug has [stayed open for over a decade in `System.Data.Sqlite`](https://system.data.sqlite.org/home/info/283344397b)
If ShareX runs into any further issues with `System.Data.Sqlite`, I'm happy to send a PR to switch it over.
This change has been tested on SMB3 shares and works on both network drive …

Restore UNC path support by parsing connection string with .NET

---

ShareX.UploadersLib/CustomUploader/CustomUploaderItem.cs

Handle import of old custom uploader files, between `12.3.1` (exclusive) and `13.7.1` (inclusive).
The root cause of this issue seems to stem from the upgrade to .NET 9, this does not fix that and only mitigates this specific issue.
This PR mitigates #8070

fix: handle old custom uploader without the field Data
