InnoSetup/ShareX setup.iss, ShareX.HelpersLib/Forms/MonitorTestForm.fr.resx, ShareX.HelpersLib/Properties/Resources.fr.resx, ShareX.HelpersLib/ShareX.HelpersLib.csproj, ShareX.HistoryLib/ShareX.HistoryLib.csproj, ShareX.ImageEffectsLib/ShareX.ImageEffectsLib.csproj, ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj, ShareX.Setup/Program.cs, ShareX.UploadersLib/Forms/JiraUpload.fr.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.fr.resx, ShareX.UploadersLib/Properties/Resources.fr.resx, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/Enums.cs, ShareX/Forms/ApplicationSettingsForm.fr.resx, ShareX/Forms/ScreenColorPicker.fr.resx, ShareX/Forms/TaskSettingsForm.fr.resx, ShareX/Forms/WatchFolderForm.fr.resx, ShareX/LanguageHelper.cs, ShareX/Program.cs, ShareX/Properties/Resources.fr.resx, ShareX/ShareX.csproj
some corection and some trick: Try to set the long sentences on 2 lines.
=> French Translation

ShareX.HelpersLib/Colors/ColorPickerForm.zh-CN.resx, ShareX.HelpersLib/DNS/DNSChangerForm.zh-CN.resx, ShareX.HelpersLib/Forms/MonitorTestForm.zh-CN.resx, ShareX.HelpersLib/Properties/Resources.zh-CN.resx, ShareX.HistoryLib/HistoryForm.zh-CN.resx, ShareX.HistoryLib/Properties/Resources.zh-CN.resx, ShareX.ImageEffectsLib/Properties/Resources.zh-CN.resx, ShareX.ScreenCaptureLib/Properties/Resources.zh-CN.resx, ShareX.UploadersLib/Controls/AccountTypeControl.zh-CN.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.zh-CN.resx, ShareX.UploadersLib/Properties/Resources.zh-CN.resx, ShareX/Forms/AboutForm.zh-CN.resx, ShareX/Forms/AfterCaptureForm.zh-CN.resx, ShareX/Forms/ApplicationSettingsForm.zh-CN.resx, ShareX/Forms/ClipboardFormatForm.zh-CN.resx, ShareX/Forms/MainForm.zh-CN.resx, ShareX/Forms/ScreenColorPicker.zh-CN.resx, ShareX/Forms/TaskSettingsForm.zh-CN.resx, ShareX/Forms/WatchFolderForm.zh-CN.resx, ShareX/Properties/Resources.zh-CN.resx
Simplified Chinese (zh-cn) update
-Corrected translation appeared in the space problem
-Fixed some translation does not comply with the actual
=> Simplified Chinese (zh-cn) update

ShareX.UploadersLib/Forms/UploadersConfigForm.zh-CN.resx, ShareX.UploadersLib/Properties/Resources.zh-CN.resx
=> Updated Simplified Chinese

ShareX/Controls/HotkeySelectionControl.cs.resx, ShareX/Forms/AboutForm.cs.resx, ShareX/Forms/ActionsForm.cs.resx, ShareX/Forms/AfterCaptureForm.cs.resx, ShareX/Forms/AfterUploadForm.cs.resx, ShareX/Forms/ApplicationSettingsForm.cs.resx, ShareX/Forms/AutoCaptureForm.cs.resx, ShareX/Forms/BeforeUploadForm.cs.resx, ShareX/Forms/ClipboardFormatForm.cs.resx, ShareX/Forms/EncoderProgramForm.cs.resx, ShareX/Forms/FileExistForm.cs.resx, ShareX/Forms/HotkeySettingsForm.cs.resx, ShareX/Forms/MainForm.cs.resx, ShareX/Forms/ScreenColorPicker.cs.resx, ShareX/Forms/ScreenRegionForm.cs.resx, ShareX/Forms/TaskSettingsForm.cs.resx, ShareX/Forms/VideoEncodersForm.cs.resx, ShareX/Forms/WatchFolderForm.cs.resx, ShareX/Properties/Resources.cs.resx
Sorry, my GitHub desktop app was acting strange before, here it is in one commit.
=> Czech Translation

ShareX/Forms/MainForm.de.resx, ShareX/Forms/TaskSettingsForm.de.resx
Hey there,
thanks for the awesome tool you're making! I fixed some spelling & grammar errors in the German translation.
Cheers,
Max
=> Improve german translation

ShareX/Controls/HotkeySelectionControl.pl.resx, ShareX/Forms/AboutForm.pl.resx, ShareX/Forms/ActionsForm.pl.resx, ShareX/Forms/AfterCaptureForm.pl.resx, ShareX/Forms/AfterUploadForm.pl.resx, ShareX/Forms/ApplicationSettingsForm.pl.resx, ShareX/Properties/Resources.pl.resx
=> Initial commit to Polish translation

ShareX.HistoryLib/HistoryForm.pl.resx, ShareX.UploadersLib/Controls/AccountTypeControl.pl.resx, ShareX.UploadersLib/Controls/AccountsControl.pl.resx, ShareX/Controls/HotkeySelectionControl.pl.resx, ShareX/Forms/AfterCaptureForm.pl.resx, ShareX/Forms/ApplicationSettingsForm.pl.resx, ShareX/Forms/AutoCaptureForm.pl.resx, ShareX/Forms/BeforeUploadForm.pl.resx, ShareX/Forms/ClipboardFormatForm.pl.resx, ShareX/Forms/EncoderProgramForm.pl.resx, ShareX/Forms/FileExistForm.pl.resx, ShareX/Forms/HotkeySettingsForm.pl.resx, ShareX/Forms/MainForm.pl.resx, ShareX/Forms/ScreenColorPicker.pl.resx, ShareX/Forms/ScreenRegionForm.pl.resx, ShareX/Forms/VideoEncodersForm.pl.resx, ShareX/Forms/WatchFolderForm.pl.resx
Haven't got much time, but many of the most important strings should be
translated now. :)
=> Next part of Polish translation.

ShareX.HelpersLib/Forms/ClipboardContentViewer.ko-KR.resx, ShareX.HelpersLib/Forms/ErrorForm.ko-KR.resx, ShareX.HelpersLib/Forms/HashCheckForm.ko-KR.resx, ShareX.HelpersLib/Properties/Resources.ko-KR.resx, ShareX.HelpersLib/UpdateChecker/DownloaderForm.ko-KR.resx, ShareX.HistoryLib/ImageHistoryForm.ko-KR.resx, ShareX.ScreenCaptureLib/Properties/Resources.ko-KR.resx, ShareX.UploadersLib/Controls/AccountTypeControl.ko-KR.resx, ShareX.UploadersLib/Controls/OAuthControl.ko-KR.resx, ShareX.UploadersLib/Forms/DropboxFilesForm.ko-KR.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.ko-KR.resx, ShareX.UploadersLib/Forms/UserPassBox.ko-KR.resx, ShareX.UploadersLib/Properties/Resources.ko-KR.resx, ShareX/Forms/AfterCaptureForm.ko-KR.resx, ShareX/Forms/ApplicationSettingsForm.ko-KR.resx, ShareX/Forms/FileExistForm.ko-KR.resx, ShareX/Forms/MainForm.ko-KR.resx, ShareX/Forms/TaskSettingsForm.ko-KR.resx, ShareX/Properties/Resources.ko-KR.resx
Many out-of-context translations, mistranslations are fixed and coherency was gained.
=> Revised Korean Translations.

ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx
I have added in the new Frankfurt AWS endpoint for S3 uploads, I have added it the order that it shows in the AWS console after EU Ireland.
=> Added AWS S3 Endpoint for EU Frankfurt Region to resolve #560

ShareX.HelpersLib/Printer/PrintTextForm.nl-NL.resx, ShareX.HelpersLib/Properties/Resources.nl-NL.resx, ShareX.HistoryLib/ImageHistoryForm.nl-NL.resx, ShareX.HistoryLib/Properties/Resources.nl-NL.resx, ShareX.ScreenCaptureLib/Properties/Resources.nl-NL.resx, ShareX.ScreenCaptureLib/Screencast/FFmpegOptionsForm.nl-NL.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.nl-NL.resx, ShareX/Forms/AboutForm.nl-NL.resx, ShareX/Forms/ActionsForm.nl-NL.resx, ShareX/Forms/ApplicationSettingsForm.nl-NL.resx, ShareX/Forms/BeforeUploadForm.nl-NL.resx, ShareX/Forms/ClipboardFormatForm.nl-NL.resx, ShareX/Forms/EncoderProgramForm.nl-NL.resx, ShareX/Forms/HotkeySettingsForm.nl-NL.resx, ShareX/Forms/MainForm.nl-NL.resx, ShareX/Forms/TaskSettingsForm.nl-NL.resx, ShareX/Properties/Resources.nl-NL.resx
- Polished up some translation parts: clarification, shortening, ...
- Added some missing translations that have been added in the past two
weeks.
@Jaex see Steam chat for a link to a folder with some screenshots that indicate label/textbox length issues with the Dutch translation, as well as some parts that seem to be untranslated.
=> Dutch polishing

ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/FileUploaders/VideoBin.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/UploadTask.cs
Add support for videobin.org as requested in #714
=> Add VideoBin support

ShareX.HelpersLib/Colors/GradientPickerForm.fr.resx, ShareX.HelpersLib/DNS/DNSChangerForm.fr.resx, ShareX.HelpersLib/Forms/ClipboardContentViewer.fr.resx, ShareX.HelpersLib/Printer/PrintForm.fr.resx, ShareX.HelpersLib/Properties/Resources.fr.resx, ShareX.HistoryLib/HistoryForm.fr.resx, ShareX.HistoryLib/ImageHistoryForm.fr.resx, ShareX.ScreenCaptureLib/Properties/Resources.fr.resx, ShareX.UploadersLib/FTPClient/FTPClientForm.fr.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.fr.resx, ShareX.UploadersLib/Forms/UserPassBox.fr.resx, ShareX.UploadersLib/Properties/Resources.fr.resx, ShareX/Forms/ApplicationSettingsForm.fr.resx, ShareX/Forms/FileExistForm.fr.resx, ShareX/Forms/HotkeySettingsForm.fr.resx, ShareX/Forms/MainForm.fr.resx, ShareX/Forms/TaskSettingsForm.fr.resx, ShareX/Forms/VideoEncodersForm.fr.resx, ShareX/Properties/Resources.fr.resx
Added missing accents, new translations and done some corrections / improvements.
=> French Translation update

ShareX.HelpersLib/Properties/Resources.nl-NL.resx, ShareX.ScreenCaptureLib/Screencast/FFmpegOptionsForm.nl-NL.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.nl-NL.resx, ShareX/Forms/AboutForm.nl-NL.resx, ShareX/Forms/MainForm.nl-NL.resx, ShareX/Forms/TaskSettingsForm.nl-NL.resx, ShareX/Forms/WebpageCaptureForm.nl-NL.resx, ShareX/Properties/Resources.nl-NL.resx
Added all missing strings for Dutch again.
=> Updated Dutch translations for V10

ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX.UploadersLib/URLShorteners/QRnetURLShortener.cs, ShareX/UploadTask.cs
Tested and working QR.net URL shortener
Example URL: http://qr.net/XZr2
=> Add QR.net URL Shortener

ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX.UploadersLib/URLShorteners/VURLShortener.cs, ShareX/UploadTask.cs
VURL.com URL Shortener Tested and Working
Test URL: http://vurl.com/YEVRM
=> Add VURL.com URL Shortener

ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX.UploadersLib/URLShorteners/TwoGPURLShortener.cs, ShareX/UploadTask.cs
Add 2.gp as a URL Shortener provider
Tested and Working
Test URL: http://2.gp/Gftf
=> Add 2.gp URL Shortener

ShareX.UploadersLib/FileUploaders/OwnCloud.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/UploadersConfig.cs, ShareX/UploadTask.cs
Adds a small button to the ownCloud config page to allow compatibility with versions 8.1 and above, mainly to fix #784
=> Adds Compatibility button for ownCloud versions 8.1+ to fix #784

ShareX.HelpersLib/Properties/Resources.fr.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.fr.resx, ShareX/Forms/MainForm.fr.resx, ShareX/Forms/TaskSettingsForm.fr.resx, ShareX/Properties/Resources.fr.resx
Some corrections, add missing translations and remove those that no longer existed.
PS: We can translate "Disable hotkeys" but not "Enable hotkeys"
=> Update French Translation

ShareX.UploadersLib/APIKeys/APIKeys.cs, ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/ImageUploaders/SomeImage.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/UploadTask.cs
Added SomeImage image uploader. As requested by #816 
Test Image: http://someimage.com/DMmib1K
Requires Application API key, which can be requested for free, I have added the entry to APIKeys.cs
API Key request: https://someimage.com/api
=> Add SomeImage image uploader

ShareX/Forms/MainForm.cs
=> Auto adjust menu to contents and set minimum

InnoSetup/Recorder devices setup.iss
=> Add 64-bit Architecture Support

ShareX.ScreenCaptureLib/RegionHelpers/ResizeManager.cs, ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj
Allows two arrow keys to be pressed to allow diagonal movement during region selection.
__8 direction movement rather than just 4__
=> multi direction arrow key movement

ShareX.HelpersLib/Extensions/StringExtensions.cs
=> fix comparison to allow match at beginning

ShareX.ScreenCaptureLib/Forms/RectangleRegion.cs, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/RegionHelpers/AreaManager.cs
related #926 
Changed from <kbd>Insert</kbd> and <kbd>End</kbd> to <kbd>Insert</kbd> and <kbd>Delete</kbd>
__Quick mode__
<kbd>Insert</kbd> - Start region selection
<kbd>Insert</kbd> - Stop region selection
<kbd>Delete</kbd> - Cancel region selection
__Multi region mode__
<kbd>Insert</kbd> - Start region selection
<kbd>Insert</kbd> - Stop region selection
<kbd>Insert</kbd> - Select/Deselect region
<kbd>Delete</kbd> - Cancel region selection
__Keyboard and Mouse switching scenarios__
<kbd>Left click</kbd> - Updated to work with <kbd>Insert</kbd> and selection starting and stopping
=> change to insert and delete

ShareX/ApplicationConfig.cs
Noticed this entirely on a fluke. Just doing my part to help. Great application!
=> Typo in Advanced Application Settings

ShareX.ScreenCaptureLib/Screencast/FFmpegOptionsForm.pt-BR.resx, ShareX/Forms/ApplicationSettingsForm.pt-BR.resx, ShareX/Forms/MainForm.pt-BR.resx
Note: There is still one last string that we didn't figure it out in time
=> Final pt-br translation

ShareX.HelpersLib/Properties/Resources.nl-NL.resx, ShareX.IRCLib/IRCClient/IRCClientForm.nl-NL.resx, ShareX.IRCLib/Properties/Resources.nl-NL.resx, ShareX.MediaLib/Forms/VideoThumbnailerForm.nl-NL.resx, ShareX.MediaLib/Properties/Resources.nl-NL.resx, ShareX.ScreenCaptureLib/Properties/Resources.nl-NL.resx, ShareX.ScreenCaptureLib/Screencast/FFmpegOptionsForm.nl-NL.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.nl-NL.resx, ShareX.UploadersLib/Forms/UserPassBox.nl-NL.resx, ShareX.UploadersLib/Properties/Resources.nl-NL.resx, ShareX/Forms/AboutForm.nl-NL.resx, ShareX/Forms/ApplicationSettingsForm.nl-NL.resx, ShareX/Forms/ChromeForm.nl-NL.resx, ShareX/Forms/FirstTimeConfigForm.nl-NL.resx, ShareX/Forms/MainForm.nl-NL.resx, ShareX/Forms/ScreenRecordForm.nl-NL.resx, ShareX/Forms/TaskSettingsForm.nl-NL.resx, ShareX/Properties/Resources.nl-NL.resx
Updated the Dutch language forms to hold all new added translations.
=> Dutch language update

ShareX.HelpersLib/ExternalProgram.cs, ShareX/Forms/ActionsForm.Designer.cs, ShareX/Forms/ActionsForm.cs, ShareX/Forms/ActionsForm.resx, ShareX/WorkerTask.cs
Added HiddenWindow option for ExternalProgram
=> Added HiddenWindow

ShareX.UploadersLib/Enums.cs, ShareX.UploadersLib/FileUploaders/PomfCat.cs, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/WorkerTask.cs
=> Pomf.cat Uploader Support

ShareX.UploadersLib/FileUploaders/Pomf.cs
Remove matu.red, pantsu.cat, sheesh.in
Add catgirlsare.sexy, cuntflaps.me
=> Update listing of pomf clones.

ShareX.UploadersLib/FileUploaders/Pomf.cs
pomf.io is now strictly https. did it right this time? :3
=> pomf.io changes

ShareX.UploadersLib/Forms/UploadersConfigForm.resx
It looks like my resx file was somehow getting messed up, I reverted it and put the Streamable changes in by hand.
=> Fix broken UploadersConfigForm

ShareX.UploadersLib/FileUploaders/Pomf.cs
I have moved pomf.io to pomf.is.
=> changed pomf.io to pomf.is

ShareX/UploadManager.cs
`Clipboard.GetImage()` discards the alpha channel and turns all transparent pixels to black. I committed some extra code that will handle 24bpp and keep alpha transparency when uploading.
note: the preview window still shows black and should implement these new changes as well to display transparent pixels, perhaps moving this code into an utility function and use that rather than Clipboard.GetImage to avoid code duplication.
=> Fixed transparency for clipboard upload

ShareX.UploadersLib/FileUploaders/Pomf.cs
pomf.pl merged into pomf.io/pomf.is
=> removed pomf.pl

ShareX.HelpersLib/Forms/QRCodeForm.cs
My Number One Annoyance Recently
=> Automatically fill QR window with Clipboard Content

ShareX.HistoryLib/ImageHistoryForm.de.resx
Fixed two german translations.
=> Fixed german translations

ShareX.UploadersLib/FileUploaders/Pomf.cs
=> Update catgirlsare.sexy pomf clone URL

ShareX.HelpersLib/SingleInstanceApplication/ApplicationInstanceManager.cs
The problem is that multiple context menu selections spawn multiple .exe
(invoked). Each invoked .exe sets the `InstanceProxy` variables in the
running .exe and tells it to start a thread to process. But, there is no
waiting, so the `InstanceProxy` variables get clobbered before the spawned
thread can process them.
This fix uses a semaphore to control the invoked .exe. There is only one
entry allowed forcing invoked .exe to wait until any other invoked .exe
is finished running and releases the semaphore.
Fixes #770
=> Handle multiple context menu selections - Fixes #770

Greenshot.ImageEditor/Forms/ImageEditorForm.cs
Disposing here causes errors when trying to save the image
=> Don't dispose the surface

ShareX/WorkerTask.cs
Current error looks like this:
=> Fix swapped message box text and caption

ShareX.UploadersLib/FileUploaders/FTP.cs
Cast to correct stream type. Also log result of transfer.
Probable fix for #1383
=> Use FtpDataStream

ShareX.HelpersLib/Forms/DebugForm.fr.resx
FIX translation:
- Removed the spacing incorrect
=> FIX translation

ShareX.UploadersLib/SharingServices/StumbleUponSharingService.cs
=> Fixing incorrect UrlFormatString for StumbleUponSharingService

ShareX.HelpersLib/Properties/Resources.de.resx
There was a minor typo in the update notification I noticed when it asked me to update.
=> Fixed typo in german update notice

ShareX.UploadersLib/Forms/UploadersConfigForm.cs
Fix text (txtJiraConfigHelp):
- `howto` to `how to`
=> Fix text (txtJiraConfigHelp)

ShareX.HelpersLib/Forms/DebugForm.ru.resx, ShareX.HelpersLib/Properties/Resources.ru.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.ru.resx, ShareX.UploadersLib/Properties/Resources.ru.resx, ShareX/Forms/ApplicationSettingsForm.ru.resx, ShareX/Forms/MainForm.ru.resx, ShareX/Forms/QuickTaskInfoEditForm.ru.resx, ShareX/Forms/QuickTaskMenuEditorForm.ru.resx, ShareX/Properties/Resources.ru.resx
Added missing untranslated fields.
=> Updated Russian translation

ShareX.HelpersLib/Properties/Resources.de.resx, ShareX/Forms/ApplicationSettingsForm.de.resx, ShareX/Forms/QuickTaskInfoEditForm.de.resx, ShareX/Forms/QuickTaskMenuEditorForm.de.resx
I don't know if the newly generated QuickTask....de.resx need to be referenced somewhere, I just commited the translations.
=> Added missing german translations

ShareX.HelpersLib/Forms/DebugForm.de.resx, ShareX.HelpersLib/Printer/PrintForm.de.resx, ShareX.HelpersLib/Properties/Resources.de.resx, ShareX.HistoryLib/ImageHistoryForm.de.resx, ShareX.HistoryLib/Properties/Resources.de.resx, ShareX.ScreenCaptureLib/Properties/Resources.de.resx, ShareX/Forms/ApplicationSettingsForm.de.resx, ShareX/Forms/AutoCaptureForm.de.resx, ShareX/Forms/ClipboardFormatForm.de.resx, ShareX/Forms/QuickTaskInfoEditForm.de.resx, ShareX/Forms/QuickTaskMenuEditorForm.de.resx, ShareX/Properties/Resources.de.resx
Some were a bit off or way to forced to be german..
Also translated some of the new labels
=> Updated german translations

ShareX.UploadersLib/FileUploaders/Lithiio.cs
Added a domain, and the 'i' sub domain configurations.
Changed to building the URL locally.
=> Updated URL's and URL handling.

ShareX/Forms/MainForm.Designer.cs, ShareX/Forms/MainForm.cs
=> Add support for context menu keyboard key to uploads listview

ShareX.UploadersLib/FileUploaders/Dropfile.cs
Dropfile.to changed their api url. Quick pull request to address this.
=> Updated dropfile.to api url. fixes #1648

ShareX.HelpersLib/Helpers/Helpers.cs, ShareX.HelpersLib/Native/NativeMethods.cs, ShareX.HelpersLib/Native/NativeMethods_Helpers.cs
=> Files and folders are now opened in the default filemanager.

ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Properties/Resources.Designer.cs, ShareX.UploadersLib/Properties/Resources.resx, ShareX/Forms/HotkeySettingsForm.cs, ShareX/Forms/QuickTaskMenuEditorForm.cs, ShareX/Properties/Resources.Designer.cs, ShareX/Properties/Resources.resx
Are the names for the localization variables okay?
=> Added confirmation dialogs to two "Reset" buttons.

ShareX/TaskManager.cs
Only open the "After upload" window if the task was an upload task.
=> Fixes #1837

ShareX.HelpersLib/Cryptographic/TranslatorHelper.cs
It is recommended to dispose MemoryStream objects after using them
=> Dispose MemoryStream objects after using them

Greenshot.ImageEditor/Drawing/SpeechbubbleContainer.cs
=> Don't update font every Draw

ShareX.UploadersLib/FileUploaders/Pomf.cs
nya.is is a new pomf host [written in crystal](https://github.com/nya/cpomf)
=> added nya.is

ShareX.UploadersLib/FileUploaders/OwnCloud.cs
All it needed was a "OCS-APIREQUEST" header: https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L183
=> Fixed #2160

ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/TextUploaders/GitHubGist.cs, ShareX.UploadersLib/UploadersConfig.cs
Added anonymous Github Gist Enterprise support.
Requested in #2149
=> Added Github Gist Enterprise support

ShareX.UploadersLib/FileUploaders/AzureStorage.cs
=> Add Content-Type headers to Azure Blobs

ShareX.HelpersLib/Helpers/CaptureHelpers.cs
=> Actions toolbar can now be placed on other monitors.

ShareX.UploadersLib/ImageUploaders/Chevereto.cs
Change to ssl to change the URL.
=> API address update

ShareX.UploadersLib/ImageUploaders/Chevereto.cs
Can not access or is not the program.
=> Can not access or is not the program.

ShareX.UploadersLib/FileUploaders/Plik.cs, ShareX.UploadersLib/FileUploaders/PlikSettings.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx
- added the ability to upload files with an infinity expire time
- adjusted the default ttl
=> Plik FileUploader changes

ShareX.HelpersLib/Colors/GradientPickerForm.zh-CN.resx, ShareX.HelpersLib/Properties/Resources.zh-CN.resx, ShareX.HistoryLib/HistoryForm.zh-CN.resx, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.zh-CN.resx, ShareX.ScreenCaptureLib/Forms/WebpageCaptureForm.zh-CN.resx, ShareX.ScreenCaptureLib/Properties/Resources.zh-CN.resx, ShareX.UploadersLib/Forms/JiraUpload.zh-CN.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.zh-CN.resx, ShareX.UploadersLib/Properties/Resources.zh-CN.resx, ShareX/Forms/ActionsToolbarEditForm.zh-CN.resx, ShareX/Forms/AfterCaptureForm.zh-CN.resx, ShareX/Forms/ApplicationSettingsForm.zh-CN.resx, ShareX/Forms/AutoCaptureForm.zh-CN.resx, ShareX/Forms/MainForm.zh-CN.resx, ShareX/Forms/TaskSettingsForm.zh-CN.resx, ShareX/Properties/Resources.zh-CN.resx
=> Updating Chinese

ShareX.HelpersLib/Properties/Resources.it-IT.resx, ShareX.MediaLib/Forms/ImageCombinerForm.it-IT.resx, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.it-IT.resx, ShareX.ScreenCaptureLib/Forms/ScrollingCaptureForm.it-IT.resx, ShareX.ScreenCaptureLib/Forms/WebpageCaptureForm.it-IT.resx, ShareX.UploadersLib/Forms/ResponseForm.it-IT.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.it-IT.resx, ShareX/Forms/ApplicationSettingsForm.it-IT.resx, ShareX/Forms/FirstTimeConfigForm.it-IT.resx, ShareX/Forms/TaskSettingsForm.it-IT.resx
Fixed typos and too long strings.
=> Updated Italian Translation

ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
tsmiTips is only initialised in AnnotationMode
=> Fix error when pressing F1 in non-Annotation mode

ShareX.DesktopBridgeHelper/App.config, ShareX.DesktopBridgeHelper/Program.cs, ShareX.DesktopBridgeHelper/ShareX.DesktopBridgeHelper.csproj, ShareX/Enums.cs, ShareX/Forms/ApplicationSettingsForm.cs, ShareX/Forms/FirstTimeConfigForm.cs, ShareX/IntegrationHelpers.cs, ShareX/Properties/Resources.Designer.cs, ShareX/Properties/Resources.resx, ShareX/ShareX.csproj, ShareX/StartupManagers/CentennialStartupManager.cs, ShareX/StartupManagers/DesktopStartupManager.cs, ShareX/StartupManagers/GenericStartupManager.cs, ShareX/StartupManagers/IStartupManager.cs, ShareX/StartupManagers/StartupManagerFactory.cs, ShareX/StartupManagers/SteamDesktopManager.cs
This is a PR to get comments, reviews and track progress on this work. Only to be merged when ready.
=> [WIP - DO NOT MERGE] Refactor Start with Windows settings into a factory and interface

ShareX/StartupManagers/GenericStartupManager.cs
This shoulnd't change something on Windows 10, but it was effectively breaking the program in Windows 7
=> Add null check for status variable

ShareX.HistoryLib/HistoryForm.Designer.cs, ShareX.HistoryLib/HistoryForm.cs
Drag and drop of entries in history list view copies file to drop location.
Closes #1550
=> Add drag and drop from history window

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs, ShareX.ScreenCaptureLib/RegionCaptureOptions.cs, ShareX.ScreenCaptureLib/RegionCaptureTasks.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX/CaptureHelpers/CaptureRegion.cs
Now user can change is editor window should be started maximized or not from toolbar options menu.
=> Added option to start image editor window maximized

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs, ShareX.ScreenCaptureLib/RegionCaptureOptions.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
Added fullscreen editor mode option in case user want to use it same as before.
Fixed exception which happens if user close ShareX while editor is open.
=> Added editor mode fullscreen option

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
It should not take multiple monitors into account there
=> Fix FPS indicator in windowed annotate

ShareX.HelpersLib/Extensions/Extensions.cs, ShareX/ApplicationConfig.cs, ShareX/Enums.cs, ShareX/Forms/MainForm.Designer.cs, ShareX/Forms/MainForm.cs, ShareX/Forms/MainForm.resx
User can select to have main form image preview pane at the side or at the bottom.
Closes #1943
=> Allow placing image preview pane on bottom

ShareX.ScreenCaptureLib/Forms/CanvasSizeForm.ru.resx, ShareX.ScreenCaptureLib/Forms/ImageSizeForm.ru.resx, ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX.ScreenCaptureLib/ShareX.ScreenCaptureLib.csproj, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.ru.resx, ShareX.UploadersLib/Helpers/CustomUploaderItem.cs, ShareX.UploadersLib/Properties/Resources.Designer.cs, ShareX.UploadersLib/Properties/Resources.resx, ShareX.UploadersLib/Properties/Resources.ru.resx, ShareX/Forms/MainForm.ru.resx
Improve translation support
Update russian translation
=> Translation improvements and updates

ShareX.HelpersLib/Colors/GradientPickerForm.Designer.cs, ShareX.HelpersLib/DNS/DNSChangerForm.Designer.cs, ShareX.HelpersLib/Forms/ClipboardContentViewer.Designer.cs, ShareX.HelpersLib/Forms/ErrorForm.Designer.cs, ShareX.HelpersLib/Printer/PrintForm.Designer.cs, ShareX.ImageEffectsLib/ImageEffectsForm.Designer.cs, ShareX.MediaLib/Forms/ImageCombinerForm.Designer.cs, ShareX.MediaLib/Forms/ImageThumbnailerForm.Designer.cs, ShareX.ScreenCaptureLib/Forms/CanvasSizeForm.Designer.cs, ShareX.ScreenCaptureLib/Forms/ImageSizeForm.Designer.cs, ShareX.ScreenCaptureLib/Forms/ScrollingCaptureForm.Designer.cs, ShareX.UploadersLib/Forms/PuushLoginForm.Designer.cs, ShareX.UploadersLib/Forms/TwitterTweetForm.Designer.cs, ShareX/Forms/ActionsForm.Designer.cs, ShareX/Forms/AfterUploadForm.designer.cs, ShareX/Forms/ClipboardFormatForm.Designer.cs, ShareX/Forms/EncoderProgramForm.Designer.cs, ShareX/Forms/QuickTaskMenuEditorForm.Designer.cs, ShareX/Forms/TextUploadForm.Designer.cs, ShareX/Forms/WatchFolderForm.Designer.cs
As per title, this increases usability. 
In a future commit I would like to make the Escape function work on other menus such as the Application Settings and Task Settings - but I was unable to get this to work (so I gave up 👍)
-------------------
_Edit: PR #2900, what a nice round number._
=> Use Accept and Cancellation buttons where appropriate

ShareX.ScreenCaptureLib/Shapes/BaseShape.cs, ShareX.ScreenCaptureLib/Shapes/Drawing/CursorDrawingShape.cs, ShareX.ScreenCaptureLib/Shapes/Drawing/FreehandDrawingShape.cs, ShareX.ScreenCaptureLib/Shapes/Drawing/LineDrawingShape.cs, ShareX.ScreenCaptureLib/Shapes/Drawing/StepDrawingShape.cs, ShareX.ScreenCaptureLib/Shapes/Drawing/TextDrawingShape.cs
Fix resizing while panning.
Add corner moving to rectangles.
=> Fix shape moving twice when moving and panning at the same time

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
Also fix canvas jumpling once when resizing
=> Fix moving canvas offscreen when resizing

ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
Translate "Editor background color"
=> Translation update

ShareX/Properties/Resources.de.resx
Fixed some things which weren’t easy to understand in German.
=> General improvements for German translation

ShareX.HelpersLib/Printer/PrintForm.ko-KR.resx, ShareX.HelpersLib/Properties/Resources.ko-KR.resx, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.ko-KR.resx, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.ko-KR.resx, ShareX/Properties/Resources.ko-KR.resx
Also moved two Editor UI literals into a resx file.
=> Modified and added some Korean Translations

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
- fix rounding errors
- change padding method
=> Improve panning scrollbars

ShareX.HelpersLib/Properties/Resources.de.resx, ShareX.ImageEffectsLib/ImageEffectsForm.de.resx, ShareX.ImageEffectsLib/Properties/Resources.de.resx, ShareX/Forms/ApplicationSettingsForm.de.resx, ShareX/Forms/MainForm.de.resx, ShareX/Forms/TaskSettingsForm.de.resx, ShareX/Forms/WatchFolderForm.de.resx
=> Added more German translation

ShareX.UploadersLib/FileUploaders/FTPAccount.cs
https://msdn.microsoft.com/en-us/library/system.uri.originalstring(v=vs.110).aspx
https://github.com/ShareX/ShareX/issues/1590
=> Dont use canonically escaped url

ShareX.HelpersLib/Controls/ToolStripCheckedBoldRenderer.cs
=> Render main menu arrow to right #3061

ShareX.UploadersLib/FileUploaders/Lambda.cs
No longer have λ.pw -- replaced by lbda.net
=> Update Lambda URLs

ShareX.UploadersLib/Forms/OCRSpaceForm.Designer.cs, ShareX.UploadersLib/Forms/OCRSpaceForm.cs, ShareX.UploadersLib/Forms/OCRSpaceForm.resx
Takes the input of the OCR and opens a link to Google Translate with it.
=> Google Translate button for the OCR form

ShareX.UploadersLib/ImageUploaders/Chevereto.cs
=> added new chevereto host - lensdump.com

AppVeyor/after_build.ps1, ShareX.Setup/Program.cs, ShareX.Setup/WindowsStore/AppxManifest.xml
Also fix appx build issues and redirect makeappx's stdout
=> Enable building Store and Steam artifacts on all builds

ShareX.UploadersLib/OtherServices/OCRSpace.cs, ShareX/Enums.cs, ShareX/Forms/ApplicationSettingsForm.cs, ShareX/Forms/FirstTimeConfigForm.cs, ShareX/IntegrationHelpers.cs, ShareX/ShareX.csproj, ShareX/StartupManagers/CentennialStartupManager.cs, ShareX/StartupManagers/DesktopStartupManager.cs, ShareX/StartupManagers/GenericStartupManager.cs, ShareX/StartupManagers/IStartupManager.cs, ShareX/StartupManagers/StartupManagerSingletonProvider.cs, ShareX/StartupManagers/SteamStartupManager.cs
=> Remove spaghetti

ShareX.UploadersLib/FileUploaders/OwnCloud.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/UploadersConfig.cs
I noticed this _a bit_ too late, non-images do in fact produce strange previews
=> Return download link if the file is not an image

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
=> Add greenshot-like shortcuts to the region capture mode and image editor

ShareX/StartupManagers/CentennialStartupManager.cs
=> Fix centennial startup manager

ShareX.HelpersLib/UpdateChecker/DownloaderForm.cs, ShareX.Setup/InnoSetup/ShareX-setup.iss
=> Prevent the update process from recreating the desktop shortcut

ShareX/Forms/TaskSettingsForm.Designer.cs, ShareX/Forms/TaskSettingsForm.cs, ShareX/Forms/TaskSettingsForm.resx, ShareX/TaskSettings.cs, ShareX/WorkerTask.cs
=> Add option to replace non-unreserved characters by underscores

ShareX.UploadersLib/FileUploaders/GoogleCloudStorage.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs
https://storage.googleapis.com/riolu-28e3a.appspot.com/2018/04/1zStpTZ7nA.mp4
=> Google Cloud Storage: Add Live Preview URL

ShareX/Forms/ApplicationSettingsForm.resx
=> Changed 'on start minimize to tray' to 'minimize to tray on start'

ShareX.HelpersLib/UpdateChecker/GitHubUpdateChecker.cs
```
IsPortable = true;
IsPortable ? true : false; //Return true
IsPortable = false;
IsPortable ? true : false; //Return false
```
=> Remove unnecessary ternary operator

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
IsEditorMode is always false, look first "if" block
=> Remove unnecessary parameter check

ShareX.UploadersLib/FileUploaders/OneDrive.cs
=> Fix uploadSession error in OneDrive for Business

ShareX.HelpersLib/Helpers/Helpers.cs, ShareX.HelpersLib/Native/NativeConstants.cs, ShareX.HelpersLib/Native/NativeMethods.cs, ShareX/Program.cs
Universal fix, will fix any affected Form
Fixes #3341
=> Use system hand cursor

ShareX.HelpersLib/Helpers/Helpers.cs
=> Fix crash when opening screen capture form

ShareX.UploadersLib/FileUploaders/GoogleDrive.cs
=> Google Drive fix parent folder not being passed correctly

ShareX.UploadersLib/FileUploaders/Pomf.cs
Pomfe.co is now https://kyouko.se/
=> Pomfe.co domain changed

ShareX.UploadersLib/FileUploaders/Pomf.cs
=> Removed Kyouko.se

ShareX.UploadersLib/ImageUploaders/Chevereto.cs
Added img.land to Chevereto list
=> Added img.land to Chevereto list

ShareX/Forms/TaskSettingsForm.ko-KR.resx
Add korean Translation for version 12.2 Beta
=> Korean Translations for version 12.2 Beta

ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs
Removed duplicate authentication code from UploadersConfigFormHelper, now it's 25% smaller!
=> Clean up OAuth2 Uploaders

ShareX.UploadersLib/Forms/UploadersConfigForm.ko-KR.resx, ShareX/Forms/ApplicationSettingsForm.ko-KR.resx
i'm glad  shareX support Korean language
=> I fix two weird Korean translation

ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/URLShorteners/FirebaseDynamicLinksURLShortener.cs
=> Removed hardcoded app.goo.gl domain to support new domain format

ShareX/Properties/Resources.de.resx
For more consistency and correctness (I hope)
=> German grammar fixes

ShareX.HelpersLib/Colors/ColorPickerForm.zh-TW.resx
Minor updated Taiwan translation and optimized some expressions for consistency.
=> Update Taiwan Language

ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.zh-TW.resx
Updated Taiwanese translation and optimized some expressions.
=> Update TW translation

ShareX/TaskHelpers.cs, ShareX/WorkerTask.cs
Save the OCR result to the same name txt file:
=> Auto save OCR result

ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Shapes/AnnotationOptions.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
Added a shape options for step counter, where the user can set the starting value as suggested by #3611
=> added StartingStepNumber option for AnnotationOptions #3611

ShareX/Forms/AfterCaptureForm.cs
=> Auto size "After capture" list to show no scroll bar

ShareX.HistoryLib/Forms/HistoryForm.Designer.cs, ShareX.HistoryLib/Forms/HistoryForm.cs, ShareX.HistoryLib/Forms/HistoryForm.resx
Added URL filtering support to history form. It does contains check that way you can just write part of URL while filtering. Fixes #2946.
=> fixes #2946: Added URL filtering support to history form

ShareX.HelpersLib/Controls/MyListView.cs, ShareX/ApplicationConfig.cs, ShareX/TaskManager.cs
Added option to automatically select last completed task in main window task list. It helps user to see image preview of last successful screenshot upload. You can find this setting in application settings window, advanced tab. Fixes #3604.
=> fixes #3604: Added option to automatically select last completed task in main window

ShareX.ScreenCaptureLib/Forms/TextDrawingInputBox.cs
Fixes bug where entering text in the text annotation tool with a CJK IME and pressing <kbd>Enter</kbd> (to accept a suggestion) will commit the text instead of just accepting the suggestion.
Fixes #3621.
=> TextDrawingInputBox: Properly handle Enter key in CJK input

ShareX.UploadersLib/FileUploaders/GoogleCloudStorage.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/UploadersConfig.cs
=> Add support for extensionless uploads on GCS

ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/Properties/Resources.Designer.cs, ShareX.UploadersLib/Properties/Resources.resx, ShareX/Forms/AboutForm.cs, ShareX/Properties/Resources.Designer.cs, ShareX/Properties/Resources.resx
- move strings to resx
- create tokens for missing language names in about form
- mark uploader names invariant
=> Improve localization support

ShareX/UploadManager.cs
I simplified the code complexity and removed code duplicates, as suggested by CodeFactor.
=> Simplified code complexity 

ShareX.ScreenCaptureLib/Enums.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.Designer.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.resx, ShareX.ScreenCaptureLib/Screencast/FFmpegOptions.cs, ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs
RESX reeeeeeeeee
I also had to increase the real time buffer size to avoid dropped frames on my 2560x1080 monitor.
GDIGrab had some terrible FPS issues but the DirectShow devices work fine.
=> Add AMD hardware acceleration support

ShareX.UploadersLib/FileUploaders/AmazonS3.cs
[Released in September.](https://blog.digitalocean.com/introducing-spaces-sfo/)
=> Add AmazonS3 endpoint for SFO2 DigitalOcean Spaces

ShareX.UploadersLib/Forms/OCRSpaceForm.cs, ShareX.UploadersLib/Helpers/OCROptions.cs, ShareX/Forms/TaskSettingsForm.Designer.cs, ShareX/Forms/TaskSettingsForm.cs, ShareX/Forms/TaskSettingsForm.resx
**New: Automatic clipboard copy option**
**New: Disable other options when silent mode is enabled**
---------------
My only concern with this commit currently the user receives zero feedback that text is copied to the clipboard. I was going to send a simple tray notification however being an external helper library it cannot access the tray icon, so I'm not sure what is the best approach.
=> Add automatic clipboard copy option to OCR

ShareX.UploadersLib/ImageUploaders/Chevereto.cs
I have commented the website that no longer working + added the the website status.
So please double check those websites, some of the has working domain, but that domain is linked to nothing, so it shows "DNS_PROBE_FINISHED_NXDOMAIN".
some of them redirect, some of them are for sale.
to be honest I wanted to add some good websites to the list, but I don't know how to get the api.
=> Remove broken websites from Chevereto websites list.

ShareX.UploadersLib/FileUploaders/GoogleCloudStorage.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs, ShareX.UploadersLib/ImageUploaders/GooglePhotos.cs, ShareX.UploadersLib/URLShorteners/FirebaseDynamicLinksURLShortener.cs, ShareX/TaskSettings.cs
Add partial responses to those that support it.
Tweak GCS code to be more efficient, live preview is now changed with image extension hiding, early url returns.
=> Google based uploaders update

ShareX.UploadersLib/FileUploaders/GoogleCloudStorage.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx, ShareX.UploadersLib/Forms/UploadersConfigFormHelper.cs, ShareX.UploadersLib/UploadersConfig.cs
=> [GCS] Add PublicACL toggle

ShareX/Properties/Resources.tr.resx
I just saw a typo and fixed it.
The guy who prepared the translation doesn't even know the basics of our language. -.-
=> Fixing Turkish translation

ShareX.HelpersLib/Forms/ColorPickerForm.vi-VN.resx, ShareX.HelpersLib/Forms/DNSChangerForm.vi-VN.resx, ShareX.HelpersLib/Forms/MonitorTestForm.vi-VN.resx, ShareX.HelpersLib/Properties/Resources.vi-VN.resx, ShareX.HistoryLib/Forms/HistoryForm.vi-VN.resx, ShareX.HistoryLib/Forms/ImageHistorySettingsForm.vi-VN.resx, ShareX.HistoryLib/Properties/Resources.vi-VN.resx, ShareX.ImageEffectsLib/ImageEffectsForm.vi-VN.resx, ShareX.MediaLib/Forms/ImageThumbnailerForm.vi-VN.resx, ShareX.MediaLib/Properties/Resources.vi-VN.resx, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.vi-VN.resx, ShareX.ScreenCaptureLib/Properties/Resources.vi-VN.resx, ShareX.UploadersLib/Forms/CustomUploaderSettingsForm.vi-VN.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.vi-VN.resx, ShareX.UploadersLib/Properties/Resources.vi-VN.resx, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/Forms/AboutForm.vi-VN.resx, ShareX/Forms/ActionsForm.vi-VN.resx, ShareX/Forms/ActionsToolbarEditForm.vi-VN.resx, ShareX/Forms/ApplicationSettingsForm.vi-VN.resx, ShareX/Forms/FileExistForm.vi-VN.resx, ShareX/Forms/MainForm.vi-VN.resx, ShareX/Forms/TaskSettingsForm.vi-VN.resx, ShareX/Properties/Resources.vi-VN.resx
Update Vietnamese vi-VN translation to be on par with the current version
=> Update Vietnamese vi-VN translation

ShareX/Controls/TaskThumbnailView.cs, ShareX/Forms/MainForm.Designer.cs, ShareX/Forms/MainForm.cs, ShareX/Forms/MainForm.resx
All key inputs available in list view mode now also gonna work in thumbnail view mode.
=> fixed #4397: Support handling key inputs in thumbnail view mode

ShareX.UploadersLib/Forms/UploadersConfigForm.Designer.cs, ShareX.UploadersLib/Forms/UploadersConfigForm.resx
Used custom listview control to allow sorting Imgur album columns, also last column width fills empty space.
=> fixed #4217: Allow sorting Imgur albums list

ShareX.HelpersLib/Forms/ColorPickerForm.Designer.cs, ShareX.HelpersLib/Forms/ColorPickerForm.cs, ShareX.HelpersLib/Forms/ColorPickerForm.resx, ShareX.HelpersLib/Helpers/ColorHelpers.cs
Added name label to color picker tool which will find closest known color and show its name.
Video: https://jaex.getsharex.com/2019/10/vFYcZKXIGy.mp4
=> fixed #4385: Added color name label to color picker tool

ShareX.ScreenCaptureLib/Enums.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.Designer.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.cs, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.resx, ShareX.ScreenCaptureLib/Screencast/FFmpegOptions.cs, ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs
=> Add libopus as an option for ffmpeg audio codec

ShareX.HistoryLib/HistoryItemManager.cs, ShareX.HistoryLib/HistoryItemManager_ContextMenu.cs
Added support for mass copying:
-Folder paths
-File paths
-File names
-File names with extensions
=> Added support for mass copying paths

ShareX.UploadersLib/FileUploaders/AmazonS3.cs
3 new endpoints added to the list:
1. Asia Pacific (Hong Kong)
2. EU (Stockholm)
3. Middle East (Bahrain)
Fixes #4586
=> Added 3 new Amazon S3 Endpoints

ShareX.ScreenCaptureLib/Forms/TextDrawingInputBox.resx
Before the commit:
After the commit:
=> Set anchor of label to the bottom-left in TextDrawingInputBox

ShareX.UploadersLib/FileUploaders/GoogleDrive.cs
=> Fix setting permissions on Google Drive shared drives

ShareX/Forms/ApplicationSettingsForm.de.resx, ShareX/Forms/ClipboardUploadForm.de.resx, ShareX/Forms/FileExistForm.de.resx, ShareX/Forms/HotkeySettingsForm.de.resx, ShareX/Forms/MainForm.de.resx, ShareX/Forms/QuickTaskMenuEditorForm.de.resx, ShareX/Forms/TaskSettingsForm.de.resx, ShareX/Forms/WatchFolderForm.de.resx, ShareX/Properties/Resources.de.resx
- Added some new translations
- Updated some translations to match the original format (e.g. `...`, `.` and Space at the end)
=> Update German translations

ShareX.HelpersLib/Forms/ClipboardViewerForm.ja-JP.resx, ShareX.HistoryLib/Forms/HistoryForm.ja-JP.resx, ShareX.ImageEffectsLib/Forms/ImageEffectsForm.ja-JP.resx, ShareX.MediaLib/Forms/ImageThumbnailerForm.ja-JP.resx, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX/Forms/ClipboardUploadForm.ja-JP.resx, ShareX/Forms/MainForm.ja-JP.resx, ShareX/Forms/TaskSettingsForm.ja-JP.resx, ShareX/Properties/Resources.ja-JP.resx
I added some words of translation into Japanese which is based  13.2.2 dev version.
=> add Japanese translations

ShareX.HelpersLib/Properties/Resources.ja-JP.resx, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX/Forms/TaskSettingsForm.ja-JP.resx, ShareX/Properties/Resources.ja-JP.resx
translated some words into Japanese.
=> update Japanese translations

ShareX/Forms/TaskSettingsForm.de.resx
Just sounds better than the old one.
=> fiexed typo

ShareX/Properties/Resources.id-ID.resx
Added a small missing translation in Indonesia
=> Update Indonesian Translation

ShareX.HelpersLib/Properties/Resources.pt-BR.resx
=> Little typo fix.

ShareX.HelpersLib/Properties/Resources.Designer.cs, ShareX.HelpersLib/Properties/Resources.ja-JP.resx, ShareX.HelpersLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Enums.cs, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs
I added some codes to localize "Border Style" enum text.
Could  you please check and merge them?
=> localize border style

ShareX.HelpersLib/Properties/Resources.Designer.cs, ShareX.HelpersLib/Properties/Resources.ja-JP.resx, ShareX.HelpersLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX/Enums.cs, ShareX/Forms/TaskSettingsForm.cs
Translated some words into Japanese
- notification toast config in app config
- step tool in image editor
Could you please check and merge them?
=> Localize toast menu and steptool

ShareX.MediaLib/Properties/Resources.ja-JP.resx, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX/Forms/TaskSettingsForm.ja-JP.resx, ShareX/Properties/Resources.ja-JP.resx
Revise Japanese texts for OCR,
and add Japanese texts for Video capturing.
=> Revise japanese resources

ShareX.HelpersLib/Properties/Resources.tr.resx, ShareX.UploadersLib/Properties/Resources.tr.resx, ShareX/Properties/Resources.tr.resx
=> Fixed some typos

ShareX.HelpersLib/Properties/Resources.Designer.cs, ShareX.HelpersLib/Properties/Resources.resx, ShareX.HistoryLib/Forms/HistoryForm.cs
- Create ResX entries for EDataType ENUM
- Implement a lookup dictionary: enum string value => translation string
- Query the lookup with strings found in history file
Thanks OMGasm
=> Localize the Type summary in History window title

ShareX.HelpersLib/Enums.cs, ShareX.HelpersLib/Properties/Resources.ru.resx, ShareX.HistoryLib/Forms/HistoryForm.ru.resx, ShareX.HistoryLib/Forms/HistorySettingsForm.ru.resx, ShareX.HistoryLib/Forms/ImageHistorySettingsForm.ru.resx, ShareX.HistoryLib/ShareX.HistoryLib.csproj, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX/Forms/ApplicationSettingsForm.ru.resx, ShareX/Forms/FirstTimeUploadForm.ru.resx, ShareX/Forms/HotkeySettingsForm.ru.resx, ShareX/Forms/InspectWindowForm.Designer.cs, ShareX/Forms/InspectWindowForm.cs, ShareX/Forms/InspectWindowForm.resx, ShareX/Forms/InspectWindowForm.ru.resx, ShareX/Forms/MainForm.ru.resx, ShareX/Forms/TaskSettingsForm.ru.resx, ShareX/Properties/Resources.Designer.cs, ShareX/Properties/Resources.resx, ShareX/Properties/Resources.ru.resx, ShareX/ShareX.csproj
- Make InspectWindowForm localizable
- Update Russian translation
=> Improve localization

ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.ko-KR.resx
=> fix: I corrected the typo

ShareX.HelpersLib/Forms/DNSChangerForm.ja-JP.resx, ShareX.HelpersLib/Forms/GradientPickerForm.ja-JP.resx, ShareX.HelpersLib/Forms/HashCheckForm.ja-JP.resx, ShareX.HelpersLib/Properties/Resources.ja-JP.resx, ShareX.HistoryLib/Forms/HistoryForm.ja-JP.resx, ShareX.HistoryLib/Forms/HistorySettingsForm.ja-JP.resx, ShareX.HistoryLib/Forms/ImageHistorySettingsForm.ja-JP.resx, ShareX.HistoryLib/Properties/Resources.ja-JP.resx, ShareX.MediaLib/Properties/Resources.ja-JP.resx, ShareX.ScreenCaptureLib/Properties/Resources.ja-JP.resx, ShareX/Forms/ApplicationSettingsForm.ja-JP.resx, ShareX/Forms/FileExistForm.ja-JP.resx, ShareX/Forms/FirstTimeUploadForm.ja-JP.resx, ShareX/Forms/HotkeySettingsForm.ja-JP.resx, ShareX/Forms/InspectWindowForm.ja-JP.resx, ShareX/Forms/MainForm.ja-JP.resx, ShareX/Forms/QuickTaskMenuEditorForm.ja-JP.resx, ShareX/Forms/TaskSettingsForm.ja-JP.resx, ShareX/Forms/WatchFolderForm.ja-JP.resx, ShareX/Properties/Resources.ja-JP.resx
Hello,
I have translated ShareX resource files into Japanese.
It's nice to merge them before releasing official v13.6.0.
Could you please merge them?
=> Update Japanese translations for v13.6.0

ShareX.HistoryLib/Forms/HistoryForm.cs
- Make dropdown options localizable
- Fix the dropdown options not updating with history refreshes
=> Improve HistoryForm file type dropdown

ShareX.HelpersLib/Properties/Resources.Designer.cs, ShareX.HelpersLib/Properties/Resources.resx, ShareX/Enums.cs, ShareX/TaskHelpers.cs
Added "Toggle tray menu" hotkey, which can be configured like this:
=> fixed #5731: Added "Toggle tray menu" hotkey

ShareX.UploadersLib/FileUploaders/Teknik.cs
This PR fixes an issue with the request type for authetication
=> Fixed invalid request functions for Teknik

ShareX.HistoryLib/Forms/HistoryForm.cs, ShareX.HistoryLib/Forms/HistoryForm.ru.resx, ShareX.HistoryLib/Properties/Resources.Designer.cs, ShareX.HistoryLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX.ScreenCaptureLib/Shapes/Effect/BaseEffectShape.cs, ShareX.ScreenCaptureLib/Shapes/Effect/BlurEffectShape.cs, ShareX.ScreenCaptureLib/Shapes/Effect/HighlightEffectShape.cs, ShareX.ScreenCaptureLib/Shapes/Effect/PixelateEffectShape.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX.UploadersLib/Forms/YouTubeVideoOptionsForm.ru.resx, ShareX.UploadersLib/ShareX.UploadersLib.csproj, ShareX/BorderlessWindowManager.cs, ShareX/Forms/BorderlessWindowForm.ru.resx, ShareX/Forms/BorderlessWindowSettingsForm.ru.resx, ShareX/Forms/MainForm.ru.resx, ShareX/Properties/Resources.Designer.cs, ShareX/Properties/Resources.resx, ShareX/Properties/Resources.ru.resx, ShareX/ShareX.csproj
Move lines to resx
Update russian
=> Localization

ShareX.HistoryLib/Forms/HistoryForm.ru.resx, ShareX.ScreenCaptureLib/Forms/CanvasSizeForm.ru.resx, ShareX.ScreenCaptureLib/Properties/Resources.Designer.cs, ShareX.ScreenCaptureLib/Properties/Resources.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX.ScreenCaptureLib/Shapes/ShapeManagerMenu.cs, ShareX/Forms/TaskSettingsForm.ru.resx, ShareX/Properties/Resources.ru.resx
- Add "FPS Limit" line to resx
- Update Russian
=> Localization update

ShareX.HistoryLib/Properties/Resources.resx
=> Fix typo in Resources.resx

ShareX/Forms/ApplicationSettingsForm.ru.resx
=> Fix typo in ApplicationSettingsForm.ru.resx

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
PavNum keys (0 / + / -) will now work for the zoom feature
=> Allowed Zoom feature to work with PavNum keys

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs
=> Fix the magnifier grid misalignment when zooming in image editor

ShareX.ScreenCaptureLib/Forms/RegionCaptureForm.cs, ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
=> Use editor DPI when rendering final image

ShareX.UploadersLib/Forms/UploadersConfigForm.de.resx
Fixes spelling and grammar mistakes for german translation.
=> Update German translation

ShareX.HelpersLib/Forms/DebugForm.he-IL.resx, ShareX.HistoryLib/Forms/ImageHistorySettingsForm.he-IL.resx, ShareX.UploadersLib/Controls/AccountTypeControl.he-IL.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.he-IL.resx, ShareX/Forms/ApplicationSettingsForm.he-IL.resx, ShareX/Forms/HotkeySettingsForm.he-IL.resx, ShareX/Forms/MainForm.he-IL.resx, ShareX/Forms/TaskSettingsForm.he-IL.resx, ShareX/Properties/Resources.he-IL.resx
Minor proofreading fixes for various terms
=> fix: Hebrew proofreading

ShareX.HelpersLib/Properties/Resources.ru.resx
Some pretty small rusisan translation changes. Also adds `AfterCaptureTasks_BeautifyImage` entry.
=> Minor changes to russian translate

ShareX.HelpersLib/NameParser/CodeMenuEntryPixelInfo.cs
The primary need was to have the ability to obtain BGR hex colors.
=> Added support individual hex color channels for color picker parser

ShareX.UploadersLib/ShareX.UploadersLib.csproj
Update SSH.NET to the latest version https://www.nuget.org/packages/SSH.NET/2023.0.0
* Support for .NET 6, 7, and .NET Standard 2.1
* Support for RSA-SHA256/512 signature algorithms
* Support for parsing OpenSSH keys with ECDSA 256/384/521 and RSA
* Support for SHA256 and MD5 fingerprints for host key validation
* Added async support to SftpClient and SftpFileStream
* Added ISftpFile interface to SftpFile
* Removed support for old target frameworks
* Improved performance and stability
* Added the ability to set the last write and access time for Sftp files
=> Update SSH.NET to 2023.0.0

ShareX.HelpersLib/Forms/HashCheckerForm.ru.resx, ShareX.HelpersLib/Properties/Resources.ru.resx, ShareX.MediaLib/Forms/ImageBeautifierForm.Designer.cs, ShareX.MediaLib/Forms/ImageBeautifierForm.resx, ShareX.MediaLib/Forms/ImageBeautifierForm.ru.resx, ShareX.MediaLib/ShareX.MediaLib.csproj, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.ru.resx, ShareX.ScreenCaptureLib/Properties/Resources.ru.resx, ShareX/Forms/ApplicationSettingsForm.ru.resx, ShareX/Forms/HotkeySettingsForm.ru.resx, ShareX/Forms/InspectWindowForm.ru.resx, ShareX/Forms/MainForm.ru.resx, ShareX/Forms/QRCodeForm.ru.resx, ShareX/Forms/TaskSettingsForm.ru.resx, ShareX/ShareX.csproj, ShareX/Tools/PinToScreen/PinToScreenForm.ru.resx, ShareX/Tools/PinToScreen/PinToScreenOptionsForm.ru.resx
Make Image Beautifier localizable
Update Russian
=> Translation updates

ShareX.HelpersLib/Properties/Resources.he-IL.resx, ShareX.MediaLib/Forms/VideoConverterForm.he-IL.resx, ShareX.MediaLib/Properties/Resources.he-IL.resx, ShareX.ScreenCaptureLib/Forms/EditorStartupForm.he-IL.resx, ShareX.ScreenCaptureLib/Forms/FFmpegOptionsForm.he-IL.resx, ShareX.ScreenCaptureLib/Forms/ScreenRecordForm.he-IL.resx, ShareX.ScreenCaptureLib/Properties/Resources.he-IL.resx, ShareX.UploadersLib/Forms/CustomUploaderSettingsForm.he-IL.resx, ShareX.UploadersLib/Forms/JiraUpload.he-IL.resx, ShareX.UploadersLib/Forms/PuushLoginForm.he-IL.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.he-IL.resx, ShareX.UploadersLib/Properties/Resources.he-IL.resx, ShareX/Forms/AboutForm.cs, ShareX/Forms/ApplicationSettingsForm.he-IL.resx, ShareX/Forms/FirstTimeConfigForm.he-IL.resx, ShareX/Forms/InspectWindowForm.he-IL.resx, ShareX/Forms/MainForm.he-IL.resx, ShareX/Forms/QRCodeForm.he-IL.resx, ShareX/Forms/TaskSettingsForm.he-IL.resx, ShareX/Properties/Resources.he-IL.resx
Added missing and newly generated strings (new devbuild options), and updated my GitHub page
=> Translation: Hebrew missing strings

ShareX.HelpersLib/Forms/HashCheckerForm.zh-TW.resx, ShareX.HelpersLib/Forms/PrintForm.zh-TW.resx, ShareX.HelpersLib/Properties/Resources.zh-TW.resx, ShareX.HistoryLib/Properties/Resources.zh-TW.resx, ShareX.MediaLib/Forms/ImageBeautifierForm.zh-TW.resx, ShareX.ScreenCaptureLib/Forms/EditorStartupForm.zh-TW.resx, ShareX.ScreenCaptureLib/Forms/ScreenRecordForm.zh-TW.resx, ShareX.ScreenCaptureLib/Forms/ScrollingCaptureForm.zh-TW.resx, ShareX.ScreenCaptureLib/Forms/ScrollingCaptureOptionsForm.zh-TW.resx, ShareX.ScreenCaptureLib/Properties/Resources.zh-TW.resx, ShareX.UploadersLib/Forms/ResponseForm.zh-TW.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.zh-TW.resx, ShareX/Controls/HotkeySelectionControl.zh-TW.resx, ShareX/Forms/ApplicationSettingsForm.zh-TW.resx, ShareX/Forms/AutoCaptureForm.zh-TW.resx, ShareX/Forms/InspectWindowForm.zh-TW.resx, ShareX/Forms/MainForm.zh-TW.resx, ShareX/Forms/QuickTaskMenuEditorForm.zh-TW.resx, ShareX/Forms/TaskSettingsForm.zh-TW.resx, ShareX/Properties/Resources.zh-TW.resx, ShareX/Tools/PinToScreen/PinToScreenOptionsForm.zh-TW.resx
BTW source text related to Scrolling Capture seems to be missing.
=> Update zh-TW localization

ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs
=> Fix image not being inserted in center when zoom level is changed

ShareX.HelpersLib/Forms/ColorPickerForm.uk.resx, ShareX.HelpersLib/Forms/ErrorForm.uk.resx, ShareX.HelpersLib/Forms/GradientPickerForm.uk.resx, ShareX.HelpersLib/Forms/HashCheckerForm.uk.resx, ShareX.HelpersLib/Forms/InputBox.uk.resx, ShareX.HelpersLib/Properties/Resources.uk.resx, ShareX.HelpersLib/UpdateChecker/DownloaderForm.uk.resx, ShareX.HistoryLib/Properties/Resources.uk.resx, ShareX.ImageEffectsLib/Forms/ImageEffectsForm.uk.resx, ShareX.MediaLib/Forms/ImageThumbnailerForm.uk.resx, ShareX.ScreenCaptureLib/Properties/Resources.uk.resx, ShareX.UploadersLib/Forms/UploadersConfigForm.uk.resx, ShareX.UploadersLib/Properties/Resources.uk.resx, ShareX/Forms/ActionsForm.uk.resx, ShareX/Forms/AfterCaptureForm.uk.resx, ShareX/Forms/BeforeUploadForm.uk.resx, ShareX/Forms/ClipboardFormatForm.uk.resx, ShareX/Forms/FirstTimeConfigForm.uk.resx, ShareX/Forms/MainForm.uk.resx, ShareX/Forms/QuickTaskInfoEditForm.uk.resx, ShareX/Forms/TaskSettingsForm.uk.resx, ShareX/Forms/WatchFolderForm.uk.resx, ShareX/Properties/Resources.uk.resx, ShareX/Tools/OCR/OCRForm.uk.resx, ShareX/Tools/OCR/ServiceLinksForm.uk.resx, ShareX/Tools/PinToScreen/PinToScreenOptionsForm.uk.resx
* fix eng copy/paste
* fix weird machine translations
* use the same terms
* use correct grammatical cases
=> Update Ukrainian translations

ShareX.ScreenCaptureLib/Helpers/WindowsRectangleList.cs
=> Clip a child window against its parent

ShareX.HelpersLib/Properties/Resources.Designer.cs, ShareX.HelpersLib/Properties/Resources.resx, ShareX/Enums.cs, ShareX/TaskHelpers.cs
> I didnt see anything for -StopAutoCature. Is there a way to do this via command line?
Added HotKey and therefore Command Line support to stop auto capture without opening the auto capture window. I used the same clock icon for the hotkey icon resource, but this can be changed if need be. Let me know if I need to edit anything.
Thanks Jaex.
=> Implemented issue #7983 third comment request
